### PR TITLE
Make sure Popup will set the Window at the Content

### LINKED ISSUE #629: [BUG] Unable to display Lottie Animation within Popup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would like to display a Lottie animation within a popup, however, the animation is loaded only on iOS. Android and macOS do not load the Lottie Animation.

**Android** - The image is not rendered at all.
**iOS** - The image renders and animates properly.
**macOS** - The image renders without animation.

image
image
image

Please find below a couple of videos showing the issue

https://user-images.githubusercontent.com/1047398/192577026-1872d522-ec10-47d1-bf1a-985ce64643fd.mov

https://user-images.githubusercontent.com/1047398/192577040-89014a88-d76d-4951-8f79-0b82fd14384d.mp4

### Expected Behavior

It is expected the Lottie animation to be rendered properly in all platforms within a popup.

### Steps To Reproduce

1. Create a new MAUI project
2. Add CommunityToolkit.Maui nuget package
3. Add SkiaSharp.Extended.UI.Maui nuget package (preview)
4. Create a CommunityToolkit Popup view and add the following code:
`<skia:SKLottieView Source="loading.json"
                           WidthRequest="200"
                           HeightRequest="200"
                           RepeatCount="-1"
                           VerticalOptions="Center" 
            HorizontalOptions="Center"/>`
5. Use the following Lottie file as animation (Download the JSON file): https://lottiefiles.com/97952-loading-animation-blue
6. Include the json file into the folder /Resources/Raw
7. Mark the json file as build action > MauiAsset
8. Create a page with a button that shows the popup view on a click event

### Link to public reproduction project repository

https://github.com/mono/SkiaSharp.Extended/files/9577812/SKLottieViewBug.zip

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.2.0
- OS:macOS Monterey 12.6
- .NET MAUI: 6.0.486
- SkiaSharp.Extended.UI.Maui 2.0.0-preview.61
```

### Anything else?

Thanks in advance for this AMAZING library!

### LINKED ISSUE #695: [Housekeeping] Make sure Popup pass the Window from its Parent to Popup.Content
Popup doesn't set the Window automagically because it's an `Element`, because of that we need to help .NET MAUI set it, on `Popup` and `Popup.Content`.

The Windows is very important for .NET MAUI controls, it's responsible for a lot of things about the View's lifecycle.

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

.NET MAUI has the concept of `Window` inside some controls, when we implemented the `Popup` we don't care (or this concept diudn't exist yet) about it, since it should be set automagically, but this isn't the case here because `Popup` is an `Element` so we need to help the framework to set it.

 ### Linked Issues ###
 

 - Make it work for Android #629
 - Fixes #695

> From our Discord channel.

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Review by brminnick — CHANGES_REQUESTED** [review]
Hey Pedro! I just tried the reproduction sample from https://github.com/CommunityToolkit/Maui/issues/629 using the [NuGet Package from this PR](https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=80100&view=artifacts&pathAsName=false&type=publishedArtifacts) (`CommunityToolkit.Maui.Core.1.0.0-build-674.80100.nupkg`), and the iOS Lotte Animation is still frozen inside of the Popup. 

Android looks good now! 

| iOS / macOS Animation in Popup Still Frozen | Android (Looks good!) |
| --- | --- |
| ScreenFlow | ScreenFlow |

**Comment by pictos** [comment]
@brminnick thanks for testing on iOS, I'll give a try here, I hope the tooling works after this update

**Comment by pictos** [comment]
So... This is kinda funny, and I'm not sure if the bug is here or in .NET MAUI.
I downloaded the sample and added our `.Core` and `.Maui` projects. If I open the popup without a breaking point, the Lottie animation doesn't work, now if I set a break point and hit play it works.

So looks like a timing issue(?)

cc: @PureWeen

https://user-images.githubusercontent.com/20712372/194966835-50451a0f-ded4-4fda-a798-029fbe8f32c3.mp4

**Comment by brminnick** [comment]
@pictos - Can we merge this since it fixes the bug on Android? As long as we keep the Bug open, we should be good right?

**Comment by pictos** [comment]
@brminnick yes, we can. I'll create a new issue related to the Window property, and link this PR to it. I'll also do a couple more changes on the PR during this week, I found some places where this can be improved.

**Review by brminnick — DISMISSED** [review]
Approved bug fix for Android

**Review by brminnick — APPROVED** [review]

**Pull request merged**
