### PR TITLE
Fix for AvatarView child dimensions not being correctly set

### LINKED ISSUE #1930: [BUG] AvatarView padding not working if ImageSource is set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using an svg MauiImage as ImageSource of AvatarView, the image fills the entire control.

### Expected Behavior

image

I would like the image to be positioned in the center keeping some distance from the edge of the control.

### Steps To Reproduce

1. `<MauiImage Update="Resources\Images\my_image.svg" BaseSize="32,32" TintColor="#FFFFFF" />`
2. `<toolkit:AvatarView HeightRequest="45" WidthRequest="45" CornerRadius="23" VerticalOptions="Start" HorizontalOptions="Start" 
                    ImageSource="my_image.png"
                    BackgroundColor="{Binding Color}" Padding="7" BorderWidth="0"/>`

### Link to public reproduction project repository

https://github.com/filippomoretto/TestAvatarViewPadding

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.1
- OS: Windows 11
- .NET MAUI: 8.0.40
```

### Anything else?

As a workaround I tried using the border instead of the padding, but the border is placed over the image so the result is the image of the same size as the control but cropped.

`avatarImage.SetBinding(WidthRequestProperty, new Binding(nameof(WidthRequest), source: this));
		avatarImage.SetBinding(HeightRequestProperty, new Binding(nameof(HeightRequest), source: this));`

I realize that it would be enough to make a new "CircleImage" control and put the image over a circle colored according to my needs instead of using AvatarView which as the name suggests is meant for slightly different purposes.

Sorry for my English.

### PR DESCRIPTION
**Pull request by GeorgeLeithead**
### Description of Change ###

In `AvatarView` any dimension restrictions such as `Padding` or `BorderWidth` are not being applied to the child `ImageSource`, which results in the image not being sized correctly.  We now apply dimension restrictions such as `Padding` and `BorderWidth` to the child `UriImageSource` element.

Before:
image

After Fix:
image

Note that there are no updates to documentation required.

 ### Linked Issues ###
 

 - Fixes #1930 

 ### PR Checklist ###
 
 - [X] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [X] Has tests (if omitted, state reason in description)
 - [X] Has samples (if omitted, state reason in description)
 - [X] Rebased on top of `main` at time of PR
 - [X] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [X] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

 
 Tested on platforms:
- [X] Android
- [X] Windows
- [ ] iOS
- [ ] MacCatalist
- [ ] Tizen

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks @GeorgeLeithead! Could you double check the Unit Tests that are erroring?

**Comment by GeorgeLeithead** [comment]
> Thanks @GeorgeLeithead! Could you double check the Unit Tests that are erroring?

@brminnick I did have a look at the failing tests. They work as expected, pass when run locally, and the results are what are expected. However, they failed in the automated build.

**Review by brminnick — APPROVED** [review]
Thanks @GeorgeLeithead! 

No worries - I was able to reproduce the unit test failures locally and fix them accordingly. 

I basically just leveraged this updated logic for HeightRequest + WidthRequest where the unit tests check `avatarImage.WidthRequest.Should().Be(...)` and `avatarImage.HeightRequest.Should().Be(...):
https://github.com/CommunityToolkit/Maui/blob/ca6a6a2f0bf86e95bdb340d5db126fe59b41eb25/src/CommunityToolkit.Maui/Views/AvatarView.shared.cs#L365-L368

**Comment by GeorgeLeithead** [comment]
> Thanks @GeorgeLeithead! 
> 
> No worries - I was able to reproduce the unit test failures locally and fix them accordingly. 
> 
> I basically just leveraged this updated logic for HeightRequest + WidthRequest where the unit tests check `avatarImage.WidthRequest.Should().Be(...)` and `avatarImage.HeightRequest.Should().Be(...):
> https://github.com/CommunityToolkit/Maui/blob/ca6a6a2f0bf86e95bdb340d5db126fe59b41eb25/src/CommunityToolkit.Maui/Views/AvatarView.shared.cs#L365-L368

 Thanks Brandon. I would have looked at it tomorrow, but you got there already (time zone differences).

**Pull request merged**
