### PR TITLE
Improved memory performance of TextColorToGenerator

### PR DESCRIPTION
**Pull request by AllenD-MSFT**
### Description of Change ###

The LINQ Single method is subject to boxing and poor memory allocation behavior. For hot paths like this it is better to avoid boxing enumerators of built-in types and also to better to unroll LINQ queries to avoid allocation behavior that causes GC pressure.

This proposed code has the same exception characteristics as .Single so callers relying on any such behavior are unaffected.

Testing memory allocation and/or boxing is not a recommended practice so no new tests are added. Existing tests should suffice. Sample code is also not needed since this is just existing method maintenance with no change in expected behavior.

 ### Linked Issues ###

Pending: Still working out the process for this change relative to issue(s).

 - Fixes #

 ### PR Checklist ###
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: No need for a documentation change.

### CODE REVIEW

**Comment by brminnick** [comment]
Cool - thanks @AllenD-MSFT! Do you happen to have any benchmarks on this PR that we can use to promote this performance improvement?

**Comment by AllenD-MSFT** [comment]
> Cool - thanks @AllenD-MSFT! Do you happen to have any benchmarks on this PR that we can use to promote this performance improvement?

I don't. Are there instructions on generating benchmarks?

This is my first time contributing so I'm not fully versed on all the ways to work here, but happy to learn.

**Comment by brminnick** [comment]
No worries! I typically recommend using [Benchmark .NET](https://github.com/dotnet/BenchmarkDotNet) to test the before-and-after performance.

I haven't tried it, but it looks like you can also use `Microsoft.Diagnostics.Tracing.TraceEvent` to test performance on Source Generators: https://www.meziantou.net/measuring-performance-of-roslyn-source-generators.htm

Long story short, we just want to confirm that this PR does provide a performance improvement before merging it.

**Comment by AllenD-MSFT** [comment]
> No worries! I typically recommend using [Benchmark .NET](https://github.com/dotnet/BenchmarkDotNet) to test the before-and-after performance.
> 
> I haven't tried it, but it looks like you can also use `Microsoft.Diagnostics.Tracing.TraceEvent` to test performance on Source Generators: https://www.meziantou.net/measuring-performance-of-roslyn-source-generators.htm
> 
> Long story short, we just want to confirm that this PR does provide a performance improvement before merging it.

Thanks. I'll give Benchmark .NET a try.

**Comment by brminnick** [comment]
Hey @AllenD-MSFT! Any luck with the benchmarks?

**Comment by brminnick** [comment]
Hi Allen! I'm closing this PR for now. I'm happy to re-open + merge it once we have the benchmark data.

**Comment by davkean** [comment]
@brminnick I see this got closed. I work on VS perf team and this continues to show up. Looking at this sort of thing all day, I can see performs much better than the prior code.  

The current code in its worst case allocates at 229 MB/second due to it the capture, delegate and boxed enumerator. Requiring folks to prove that unwrapping LINQ into a foreach allocates and is faster seems like a high burden of proof that not even Microsoft requires on their own repositories, please reconsider merging this.

**Comment by brminnick** [comment]
Thanks for the review @davkean! Always good to hear from you!!

I'm happy to merge it with your stamp of approval 💯

**Review by brminnick — APPROVED** [review]

**Review by brminnick — DISMISSED** [review]

**Comment by AllenD-MSFT** [comment]
I changed roles right after putting this up. I devised a few benchmarks, but they weren't real-world enough to show the improvement. Unit tests are like that. I'm glad @davkean noticed and jumped in.

**Review by brminnick — APPROVED** [review]

**Pull request merged**
