### PR TITLE
Remove Null-Coalescing Assignment Operator Workaround from Sample App

### PR DESCRIPTION
**Pull request by brminnick**
### Description of Change ###

This PR Removes the Null-Coalescing Assignment Operator (`??=`) Workaround that was required for instantiating XAML fields when Nullable is enabled.
 
This workaround is now handled natively via Source Generators in .NET MAUI https://github.com/dotnet/maui/issues/1796#event-5661151291

### CODE REVIEW

**Comment by brminnick** [comment]
Closing this until .NET 6.0.2 is released.

Build logs show that `Microsoft.CodeAnalysis` DLL cannot be found in 6.0.200-preview.22055.15:
```
  CSC : warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.ConvertSwitchStatementToExpression.ConvertSwitchStatementToExpressionDiagnosticAnalyzer cannot be created from C:\Users\VssAdministrator\AppData\Local\Microsoft\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. [D:\a\1\s\samples\CommunityToolkit.Maui.Sample\CommunityToolkit.Maui.Sample.csproj]
```

**Comment by VladislavAntonyuk** [comment]
@brminnick it doesn’t work on Windows target framework (

**Comment by brminnick** [comment]
Dang - I wonder if this is a bug in MAUI's source generators?

**Comment by pictos** [comment]
@brminnick I think so, maybe we should reopen https://github.com/dotnet/maui/issues/1796 adding more info

**Pull request closed without merging**
