### PR TITLE
Improve the usage experience with CompareConverter in XAML

### LINKED ISSUE #1437: [BUG] CompareConverter - No property, BindableProperty, or event found for "ComparingValue", or mismatching type between value and property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

In spite of the comparing value having been set, it is showing a message that it was not set. 

### Expected Behavior

The expectation is the TrueObject return to the Text Property

### Steps To Reproduce

Use the code below to reproduce the issue in any page 

Page:
```xml            
<ContentPage.Resources>
        <ResourceDictionary>
            <toolkit:CompareConverter
                x:Key="SaveButtonTextCompareConverter"
                ComparingValue="0"
                ComparisonOperator="Equal"
                FalseObject="Update"
                TrueObject="Save" />
        </ResourceDictionary>
    </ContentPage.Resources>

<VerticalStackLayout Margin="10,5" Spacing="10">

        <Grid ColumnDefinitions="*, 100" ColumnSpacing="5">
            <Entry Grid.Column="0" Text="{Binding TaskItem}" />
            <Button
                Grid.Column="1"
                Text="{Binding TaskItemId, Converter={StaticResource SaveButtonTextCompareConverter}}" />
        </Grid>
</VerticalStackLayout>
```
ViewModel

```
public partial class AnyViewModel : ObservableObject
{

    public TodoViewModel(){}

    [ObservableProperty]
    private int _taskItemId;
```

### Link to public reproduction project repository

https://github.com/MarcosCostaDev/MAUI-sql-server-docker/blob/b1cdbc257396f16715184993f4f2414ec431fb9e/src/TodoMaui/Pages/TodoPage.xaml#L29-L45

### Environment

```markdown
.NET MAUI CommunityToolkit: 6.0.0
OS: Windows 11 Build 10.0.22621
.NET MAUI: 7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bijington**
### Description of Change ###

 

The aim of this PR is to simplify the usage of the `CompareConverter` through better control of implementation when inheriting form `CompareConverter`.

The current usage of the converter is as follows:

```xaml
<x:Double x:Key="ComparingValue">0.5</x:Double>
<Color x:Key="LightGreen">LightGreen</Color>
<Color x:Key="PaleVioletRed">PaleVioletRed</Color>
            
<converters:CompareDoubleToColorConverter
    x:Key="isLargerThanOneConverter"
    ComparingValue="{StaticResource ComparingValue}"
    ComparisonOperator="Greater"
    TrueObject="{StaticResource LightGreen}"
    FalseObject="{StaticResource PaleVioletRed}" />
```

If a developer tries to write `ComparingValue="0.5"` they will receive a compilation error stating:

> No property, BindableProperty, or event found for "ComparingValue", or mismatching type between value and property

This is down to the fact that `ComparingValue` is of type `IComparable` and there is no implicit conversion that can be determined between the value 0.5 (which is a `string`) to `IComparable`.

This PR makes it possible to define what type `ComparingValue` should be when inheriting from the converter. Therefore usage becomes:

### Converter definition

```csharp
public sealed class CompareDoubleToColorConverter : CompareConverter<double, Color>
{
}
```

### XAML usage

```xaml
<converters:CompareDoubleToColorConverter
    x:Key="isLargerThanOneConverter"
    ComparingValue="1"
    ComparisonOperator="Greater"
    TrueObject="LightGreen"
    FalseObject="PaleVioletRed" />
```

It might feel like a small improvement but I believe it will make quite a difference, especially when using the markup extension to define it inside the binding. The definitions become a lot more concise.

## Question

Should we go a step further and make `ComparingValue` a `BindableProperty` and allow developers to make the value dynamic through the use of bindings? I think yes but I would like to see what others think.

 ### Linked Issues ###
 

 - Fixes #1437 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
I like it! Should we update the docs to demonstrate this as the recommended way going forward to use `CompareConverter`?

**Comment by bijington** [comment]
Yes I'll update the docs to reflect this 👍

**Comment by brminnick** [comment]
Right on! I've added the https://github.com/CommunityToolkit/Maui/labels/approved and https://github.com/CommunityToolkit/Maui/labels/pending%20documentation labels for now. 

It looks like there's a missing XML comment somewhere causing the build to fail, but once that's fixed (and the docs are generated) I'm happy to approve + merge 🙌

**Comment by bijington** [comment]
Awesome thanks @brminnick. Technically this change is breaking because `CompareConverter` now takes 2 type arguments.

It went from 

```csharp
public abstract class CompareConverter<TReturnObject> : BaseConverterOneWay<IComparable, object>
```

to

```csharp
public abstract class CompareConverter<TValue, TReturnObject> : BaseConverterOneWay<TValue, object> where TValue : IComparable
```

If we want to avoid a major version now and breaking developers straightaway we could add in the following and mark it as `[Obsolete]`

```csharp
[Obsolete]
public abstract class CompareConverter<TReturnObject> : CompareConverter <IComparable, TReturnObject>
```

This would provide a more gentle break for those that are already using CompareConverter and not having an issue. What do you think?

**Comment by brminnick** [comment]
Good catch! I've added the https://github.com/CommunityToolkit/Maui/labels/breaking%20change label too.

Nah, don't worry about it. We recently merged another breaking change in #1839, so our next release will be a major version bump anyways.

We'll both just want to double check the Release Notes to ensure these PRs with the https://github.com/CommunityToolkit/Maui/labels/breaking%20change are called out 💯

**Review by brminnick — APPROVED** [review]

**Comment by bijington** [comment]
Docs are at: https://github.com/MicrosoftDocs/CommunityToolkit/pull/415

**Pull request merged**
