### PR TITLE
Update for .NET MAUI RC 1

### PR DESCRIPTION
**Pull request by brminnick**
## Description

This PR updates the following:
- Enables Unit Testing
  -  Unit Test support added in .NET MAUI RC 1: https://github.com/dotnet/sdk/issues/21845#issuecomment-943270826
- Adds Windows Support
- Adds Windows Sample App

### `azure-pipelines.yml`
  - Enable Unit Testing step
    - .NET MAUI RC 1 now supports `dotnet test`
  - Increase to Xcode 13.1
    - .NET MAUI RC 1 now supports Xcode 13.1
  - Use `macOS-latest` build host
    - The `macOS-11` build host uses Xcode 13.0
### `CommunityToolkit.Maui`
  - Add Windows support  
  - Temporarily remove `ImpliedOrderGridBehavior`
    - This behavior relies on `Layout.ChildAdded` which is currently broken in .NET MAUI RC 1: https://github.com/dotnet/maui/issues/3309
### `CommunityToolkit.Maui.UnitTests`
  - Update `Microsoft.NET.Test.Sdk` NuGet Package to  v17.0.0
  - Added `Xunit.Runner.VisualStudio` NuGet Package
  - Fix `MemberData` inputs
    - Xunit `MemberData` requires a public property
  - Remove `MultiConverterParameter_Tests.cs `
    - MultiConverter Parameter tests covered in `MultiConverter_Tests.cs`
  - Temporarily remove `ImpliedOrderGridBehavior` Unit Tests
### `CommunityToolkit.Maui.Sample`
  - Add Windows Sample

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
just curious is it rc1 or preview 10?

**Review by jfversluis — APPROVED** [review]
Looks good to me! For naming it seems the version just released is indeed preview 10. Seems there will be a 11 and then an RC. https://github.com/dotnet/maui/wiki/Roadmap

**Comment by VladislavAntonyuk** [comment]
@jfversluis this release is confusing: https://github.com/dotnet/maui/releases/tag/6.0.100-rc.1.7

**Comment by jfversluis** [comment]
Well, yes and no. What is released it usually a month old and had been tested etc. while the team is already working on the next thing. So it makes sense ;) this would then however mean that there won't be a preview 11 and we go straight to RC. 

But yeah, I tag a couple of times with new versions sometimes as well just so that it's easier to get the artifacts that way and then when something is wrong: do it again. Don't pay too much attention as long as it isn't finalized :)

**Pull request merged**
