### PR TITLE
Change the calling conditions of Popup's Dismiss method on Android

### LINKED ISSUE #2135: [BUG] [ANDROID] Popup kills application when trying to close after Activity.OnDestroy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

This behavior happens when activating in device developer options: "Dont keep activities"
When a Popup is open and the main activity gets destroyed (by for example locking the device), unlocking the device the popup disappeared. Then when trying to close the popup (as from code there is no real way of telling if the popup is still open) the application gets terminated with exception like: [mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: View=DecorView@357f8b6[MainActivity] not attached to window manager

Also: what happens with the popup? is it disposed or stuck in memory?

### Expected Behavior

The expected behavior would be that the application doesnt crash. 
This could also be resolved by beeing able to check if the popup is still open.

### Steps To Reproduce

1. Activate  "Dont keep activities" in developer options
2. Open popup which closes by itself after for example 20 seconds
3. Lock device
4. Unlock device
5. Wait for the close code to be executed

### Link to public reproduction project repository

https://github.com/SchittkowskiMS/PopupActivityIssue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: Android 14
- .NET MAUI: 8.0.71
```

### Anything else?

-

### PR DESCRIPTION
**Pull request by cat0363**
This PR resolves the issue where an exception occurs when the Popup's Close method is called when the Activity that displays the Popup has already been destroyed.

 ### Description of Change ###

This issue occurs when the Popup's Dismiss method is called when the Activity that displays the Popup has already been discarded.

 [mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: View=DecorView@357f8b6[MainActivity] not attached to window manager

If the Activity that displays the Popup has already been disposed of, I will modify it so that the Dismiss method of the Popup is not called.

[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopUpHandler.android.cs]

```
	public static void MapOnClosed(PopupHandler handler, IPopup view, object? result)
	{
		var popup = handler.PlatformView;

		if (!popup.Context.GetActivity().IsDestroyed())
		{
			if (popup.IsShowing)
			{
				popup.Dismiss();
			}
		}

		view.HandlerCompleteTCS.TrySetResult();

		handler.DisconnectHandler(popup);
	}
```

 

 ### Linked Issues ###
 

 - Fixes #2135

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

Below are the verification results.
I tested the verification code for Issue #2135 by setting the time to close the Popup to 5 seconds.

https://github.com/user-attachments/assets/da2e67ac-6bd6-4f2b-871c-4ac82b0b8339

Even if the Popup's Close method is called 5 seconds after the Popup is displayed, no exception is thrown.
When you return from standby, you will see that the Activity has been newly started.

The following is the verification result when waiting 5 seconds without setting it to standby.

https://github.com/user-attachments/assets/ed840d27-2a34-4378-8a30-b62a8659df6d

You can see that the popup is closed as intended.

### CODE REVIEW

**Review by bijington — APPROVED** [review]
Thank you @cat0363

**Comment by bijington** [comment]
I assume this is ready to merge?

**Comment by cat0363** [comment]
When I checked, the following unit test failed.

CommunityToolkit.Maui.UnitTests.Views.PopupTests.PopupDismissedByTappingOutsideOfPopup

@bijington , In this unit test, does the activity exist?
If the activity does not exist, the Popup's Dismiss method will not be called, so the unit test is expected to fail with a timeout.

**Comment by cat0363** [comment]
@bijington , I mistakenly thought that the error was occurring in the unit test on the Android side.
This seems to be occurring on the macOS side, which is unrelated to this change.

> CommunityToolkit.Maui.UnitTests.Views.PopupTests.PopupDismissedByTappingOutsideOfPopup

**Comment by bijington** [comment]
@cat0363 thansk for the explanation. I'm not sure why it would be failing on macOS and not windows. I'll try and take a look this week 👍

**Comment by bijington** [comment]
The test passes locally on my mac

**Pull request merged**
