### PR TITLE
Remove popup corner rounding and shadow on iOS

### LINKED ISSUE #1452: [BUG] Popup cannot be display with right angles or rounded angles
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When displaying a CommunityToolkit.Maui.Views.Popup, I would like to be able to define the angles radius.

At this moment, it is follow the native default value, that is right angles on Android and rounded angles on iOS for instance.

On Android :
image

On iOS : 
image

### Expected Behavior

I would like to have a parameter setting the corner radius.

Or the best would be to draw ourself the view, maybe with a handler and cgrect for iOS for instance ? Any advice or help would be appreciated on this point if it is possible.

I have had a look at the code, and maybe here we could do something for iOS to draw the frame using a CGRect ?
https://github.com/CommunityToolkit/Maui/blob/3b44cc0350d57b196a967d2faa917d7cf23e27fa/src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs#L142C18-L142C18

OR if it is doing using a handler I would be happy to learn

### Steps To Reproduce

1. Get the sample project  https://github.com/espritm/Maui.Toolkit.Popup
2. Build and run, click the button, the popup is displayed
3. In Controls folder, Popup class, I would like to have a parameter or some native code pour modifiy the angles.

### Link to public reproduction project repository

https://github.com/espritm/Maui.Toolkit.Popup

### Environment

```markdown
- .NET MAUI CommunityToolkit:6.0.0
- OS:iOS, Android
- .NET MAUI:7.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cat0363**
In this PR, we will remove the rounded corners of the iOS version of Popup to make it look similar to Android and Windows.

 ### Description of Change ###

In order to remove the rounded corners of the iOS version of Popup, I modified it as follows.

[src\CommunityToolkit.Maui.Core\Views\Popup\MauiPopup.macios.cs]

    public override void ViewDidLayoutSubviews()
    {
        base.ViewDidLayoutSubviews();

        _ = View ?? throw new InvalidOperationException($"{nameof(View)} cannot be null.");

        View.Superview.Layer.CornerRadius = 0.0f;
        PresentationController?.ContainerView?.Subviews.OfType<UIImageView>().FirstOrDefault()?.RemoveFromSuperview();

        SetElementSize(new Size(View.Bounds.Width, View.Bounds.Height));
    }

The code below will remove the rounded corners.

    View.Superview.Layer.CornerRadius = 0.0f;

However, if you use only the above code, the default shadow of iOS Popup will be displayed, and it will look like the following.

Shadows are visible around the corners.
To remove this shadow, we will use the method suggested by @maonaoda.

    PresentationController?.ContainerView?.Subviews.OfType<UIImageView>().FirstOrDefault()?.RemoveFromSuperview();

You can remove the shadow using the above code.

One thing to note is that in order to round the corners of the Popup, you need to layout it as shown below.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="300,300"Color="Transparent">
        <Border StrokeShape="RoundRectangle 40,40,40,40" BackgroundColor="Red" StrokeThickness="0">
            <Grid>
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
            </Grid>
        </Border>
    </toolkit:Popup>

The following are points to keep in mind when rounding the corners of Popup.
1. Specify Transparent for Popup Color
2. Wrapping Popup content with Border
3. Set Border's StrokeShape to 0
4. Specify RoundRectangle and CorderRadius for StokeShape of Border

If the above layout is not applied, the rounded corners of the iOS version of Popup will be removed by default.

For reference, before the modification, Popup is displayed as below on iOS.

This is a breaking change as it applies to all users.

 

 ### Linked Issues ###
 

 - Fixes #1452

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

I tested it with the following layout.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="300,300"Color="Transparent">
        <Border StrokeShape="RoundRectangle 40,40,40,40" BackgroundColor="Red" StrokeThickness="0">
            <Grid>
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
                <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
            </Grid>
        </Border>
    </toolkit:Popup>

Below are the verification results.

<table>
  <tr>
    <td>[Corners rounded]</td>
    <td>[Corners right angles]</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

The following is the layout when the Popup content is not wrapped in a Border.

    <toolkit:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
        x:Class="MauiComm_VerityPopupSize.PopupPage6" Size="300,300" Color="Transparent">
        <Grid BackgroundColor="Red">
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="Start" HorizontalOptions="End" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="Start" BackgroundColor="Blue" />
            <Grid WidthRequest="10" HeightRequest="10" VerticalOptions="End" HorizontalOptions="End" BackgroundColor="Blue" />
        </Grid>
    </toolkit:Popup>

Below are the verification results.

You can see that if the Popup's content is not wrapped with a Border, the corners of the Popup will be at right angles, and if it is wrapped, the roundness of the corners of the Popup can be controlled by the StrokeShape of the Border. 

It would be desirable to be able to control the roundness of Popup corners using Popup properties, but this would require significant modification for each platform. For this reason, we propose a method to avoid this by wrapping the Popup's content in a Border and controlling the roundness of the corners using the Border's StrokeShapre.

If possible, I would like you to consider the following discussion in this PR for free customization of Popup.
https://github.com/CommunityToolkit/Maui/discussions/1461

### CODE REVIEW

**Comment by cat0363** [comment]
CornerRadius is initialized when the screen is rotated, so I will correct it and upload it again.

**Comment by cat0363** [comment]
By adding the code below, the problem with rotation was also resolved.

    View.Superview.Layer.MasksToBounds = false;

I will upload the source code again after verification.

**Comment by cat0363** [comment]
The verification videos before and after the correction are shown below.

[Case : Corners right angles]

<table>
  <tr>
    <td>[Before Fix]</td>
    <td>[After Fix]</td>
  </tr>
  <tr>
    <td><video controls width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/8d52ccd6-05b6-4e83-a08f-019cacc3266f" /></td>
    <td><video controls width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/f7d96272-1654-4326-a48f-6bbec9dfc64b" /></td>
  </tr>
</table>

[Case : Corners rounded]

<table>
  <tr>
    <td>[Before Fix]</td>
    <td>[After Fix]</td>
  </tr>
  <tr>
    <td><video controls width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/f8baaa52-e0bc-4bf3-a93f-498683b84db5" /></td>
    <td><video controls width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e0f8888a-b581-4820-9d1b-7fa1d4fa5cfc" /></td>
  </tr>
</table>

After modification, you can see that the curvature of the Popup's corners has not changed.
If Border's CornerRadius is a large value, this change in curvature will not be seen, so we verified it with a small value of 13 or less.

**Review by brminnick — APPROVED** [review]

**Comment by Toine-db** [comment]
Please check if this solution still works when showing multiple (or just 2) popups one after another.
In my case the wrong background was removed ;-)

**Comment by bijington** [comment]
> Please check if this solution still works when showing multiple (or just 2) popups one after another. In my case the wrong background was removed ;-)

This PR has been completed, if you are seeing an issue can you please open a bug at: https://github.com/CommunityToolkit/Maui/issues/new/choose

**Comment by Toine-db** [comment]
> > Please check if this solution still works when showing multiple (or just 2) popups one after another. In my case the wrong background was removed ;-)
> 
> This PR has been completed, if you are seeing an issue can you please open a bug at: https://github.com/CommunityToolkit/Maui/issues/new/choose

Thanks for the comment, I now see I put this in the wrong thread.
I should be in [#1615](https://github.com/CommunityToolkit/Maui/pull/1615)

**Pull request merged**
