### PR TITLE
#475 Fix Sample freezes on SelectAllTextBehaviorPage, fix typos

### LINKED ISSUE #475: [Bug] SelectAllTextBehaviorPage Causes Freez
### Steps to Reproduce

1. Pull current MauiToolKit Sample
2. Start Device
3. Open tab behavior
4. Open SelectAllTextBehavior

### Expected Behavior
Opens the Page SelectAllTextBehavior
### Actual Behavior
Freezes
### Basic Information

- Version with issue: current
- Last known good version: unknown
- IDE: vs22 Preview
- Platform: Windows

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

Replace Frame with Border, 
Fix typos

 ### Linked Issues ###
 

 - Fixes #475 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by pictos** [comment]
@VladislavAntonyuk this change our sample to use border and then that works again (I presume), but if the user wants to have a `Frame` on his app, the freeze will still happen? Or am I missing something?

**Review by brminnick — COMMENTED** [review]
Thanks Vlad! 

I confirmed that `SelectAllTextBehaviorPage` now works on Windows 👍 

Are you able to open `SelectAllTextBehaviorPage` on Android? The app crashes immediately as soon as I load the page in my Android emulator. Maybe it's a problem with my dev machine?

**Comment by VladislavAntonyuk** [comment]
> Thanks Vlad!
> 
> I confirmed that `SelectAllTextBehaviorPage` now works on Windows 👍
> 
> Are you able to open `SelectAllTextBehaviorPage` on Android? The app crashes immediately as soon as I load the page in my Android emulator. Maybe it's a problem with my dev machine?

yes. it opens:
image

**Comment by brminnick** [comment]
Thanks - approved! 

Looks like I need to fix my dev machine 😅

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk this change our sample to use border and then that works again (I presume), but if the user wants to have a `Frame` on his app, the freeze will still happen? Or am I missing something?

I assume yes. I tried other pages where we have Frame and they work. If I comment behaviors it still freezes. Breakpoint is not fired in Behavior, so it freezes somewhere before

**Pull request merged**
