### PR TITLE
Update ImpliedOrderGridBehavior.shared.cs

### PR DESCRIPTION
**Pull request by FirdavsIbra**
In addition, letter case should be default case, old version is pascal case.

 ### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by FirdavsIbra** [comment]
I want to know, was my commit helpful and necessary?)

**Comment by VladislavAntonyuk** [comment]
It would be nice if you fix it for all similar places. But please start from reading README file, where we describe the flow (create discussion->create bug->wait for approve->create PR)

**Comment by VladislavAntonyuk** [comment]
Please create an issue before creating a PR. Closing it for now

**Comment by FirdavsIbra** [comment]
Thank u for your answer, I try to fix bugs and will again add changes as you said before

**Pull request closed without merging**
