### PR TITLE
Feature template

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by bijington** [comment]
Is there an easy way to preview what this template will look like when we merge?

**Comment by VladislavAntonyuk** [comment]
I will create a repo to check. When it is ready I will create a final pr

**Comment by VladislavAntonyuk** [comment]
https://github.com/VladislavAntonyuk/github-templates

**Review by bijington — APPROVED** [review]
Awesome work @VladislavAntonyuk

**Comment by brminnick** [comment]
Thanks Vlad! Could you bring the bug template and the Proposal template to the Maui.Markup repo too?

**Pull request merged**
