### PR TITLE
Add consideration of FlowDirection

### LINKED ISSUE #1432: [BUG] Windows Popup control not centered after updating CommunityToolkit.Maui package to version 6.0.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I recently updated the CommunityToolkit.Maui package from version 5.3.0 to 6.0.0, and now the Popup control is no longer centered on my main page.

Setting HorizontalOptions="Center" wouldn't do anything.
I tried setting the Anchor property on xaml and on code-behind but that wasn't posable.

After some investigation, I found that the issue was caused by setting the FlowDirection property of my main content control (a Grid) to "RightToLeft". When I removed this property or set it to "LeftToRight", the Popup control was centered correctly.
(It's Like the popup being drawing from right to left)

So far it's effect on Windows apps, but not Android, and idk about IOS.

I believe this is a bug in the CommunityToolkit.Maui package 6.0.0, and I would like to report it so that it can be fixed in future releases.

Versions used:

CommunityToolkit.Maui: 6.0.0
Please let me know if you need any further information or clarification.

I hope this helps!

### Expected Behavior

The Expected Behavior should have been the same normal behavior of version 5.3.0. 
that is the Popup show at the center, not shifted to the right side of the screen.

### Steps To Reproduce

- Just create a MAUI project.
- Add the package CommunityToolkit.maui version 6.0.0
- Initialize the .NET MAUI Community Toolkit by adding the below line of code
.UseMauiCommunityToolkit()

the rest is the same in the documentation: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

Change the FlowDirection="RightToLeft" of the Main Content Control (say a Grid or a VerticalStackLayout) and some Labels or buttons.

run the project.
			

### Link to public reproduction project repository

https://github.com/uSafi/Popup-Issue-on-CommunityToolkit.Maui-version-6.0.0

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Windows 10.
It run normally on Android, IDK about IOS.
- .NET MAUI: 6.0.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cat0363**
This PR corrects the display position of Popup so that it is displayed as intended on Windows when FlowDirection is specified for Popup Content.

 ### Description of Change ###
Change the display position calculation formula as shown below depending on the FlowDirection value of Popup Content.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.windows.cs]

    public static void SetLayout(this Popup mauiPopup, IPopup popup, IMauiContext? mauiContext)
    {
        ArgumentNullException.ThrowIfNull(mauiContext);
        ArgumentNullException.ThrowIfNull(popup.Content);

        var popupParent = mauiContext.GetPlatformWindow();
        popup.Content.Measure(double.PositiveInfinity, double.PositiveInfinity);
        var contentSize = popup.Content.ToPlatform(mauiContext).DesiredSize;
        var popupParentFrame = popupParent.Bounds;
        var hSign = popup.Content.FlowDirection == Microsoft.Maui.FlowDirection.RightToLeft ? -1 : 1;

        var verticalOptions = popup.VerticalOptions;
        var horizontalOptions = popup.HorizontalOptions;
        if (IsTopLeft(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.TopEdgeAlignedLeft;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - popupParentFrame.Width * hSign) / 2;
            mauiPopup.VerticalOffset = 0;
        }
        else if (IsTop(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Top;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = 0;
        }
        else if (IsTopRight(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.TopEdgeAlignedRight;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width + popupParentFrame.Width * hSign) / 2 - contentSize.Width * hSign;
            mauiPopup.VerticalOffset = 0;
        }
        else if (IsRight(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Right;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width + popupParentFrame.Width * hSign) / 2 - contentSize.Width * hSign;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsBottomRight(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.BottomEdgeAlignedRight;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width + popupParentFrame.Width * hSign) / 2 - contentSize.Width * hSign;
            mauiPopup.VerticalOffset = popupParentFrame.Height - contentSize.Height;
        }
        else if (IsBottom(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Bottom;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = popupParentFrame.Height - contentSize.Height;
        }
        else if (IsBottomLeft(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.BottomEdgeAlignedLeft;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - popupParentFrame.Width * hSign) / 2;
            mauiPopup.VerticalOffset = popupParentFrame.Height - contentSize.Height;
        }
        else if (IsLeft(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Left;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - popupParentFrame.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsCenter(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsFillLeft(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - popupParentFrame.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsFillCenter(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsFillRight(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width + popupParentFrame.Width * hSign) / 2 - contentSize.Width * hSign;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsTopFill(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = 0;
        }
        else if (IsCenterFill(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (IsBottomFill(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = popupParentFrame.Height - contentSize.Height;
        }
        else if (IsFill(verticalOptions, horizontalOptions))
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else if (popup.Anchor is null)
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Auto;
            mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;
            mauiPopup.VerticalOffset = (popupParentFrame.Height - contentSize.Height) / 2;
        }
        else
        {
            mauiPopup.DesiredPlacement = PopupPlacementMode.Top;
        }

        omit ...
    }

hSign is 1 if FlowDirection is LeftToRight and -1 if FlowDirection is RightToLeft.
The calculation formula was modified as shown below according to the value of HorizontalOptions.

[If Start is specified for HorizontalOptions]

    mauiPopup.HorizontalOffset = (popupParentFrame.Width - popupParentFrame.Width * hSign) / 2;

[If Center is specified for HorizontalOptions]

    mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;

[If End is specified for HorizontalOptions]

    mauiPopup.HorizontalOffset = (popupParentFrame.Width + popupParentFrame.Width * hSign) / 2 - contentSize.Width * hSign;

[If Fill is specified for HorizontalOptions]

    mauiPopup.HorizontalOffset = (popupParentFrame.Width - contentSize.Width * hSign) / 2;

 

 ### Linked Issues ###
 

 - Fixes #1432

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

Below are the verification results.

[FlowDirection = "RightToLeft"]

https://github.com/CommunityToolkit/Maui/assets/125236133/70c535ab-a212-4190-8ef6-4c47fedf8e07

[FlowDirection = "LeftToRight"]

https://github.com/CommunityToolkit/Maui/assets/125236133/43f8cd77-0f2d-476e-b4e1-5a8b58588c03

You can see that both patterns display the Popup in the intended position.

The following was used for verification. 

https://github.com/cat0363/MauiIComm-VerifyPopupFlowDirection.git

### CODE REVIEW

**Comment by cat0363** [comment]
Depending on the answers to the questions in the comments below, I will revise this PR.
https://github.com/CommunityToolkit/Maui/issues/1432#issuecomment-1742383309

**Review by brminnick — CHANGES_REQUESTED** [review]
Thanks for fixing this on Windows @cat0363! 

Let's re-scope this PR to include iOS, Android, MacCatalyst and Tizen too. We want to standardize behavior across all supported platforms.

I agree that when `FlowDirection.RightToLeft` and `HorizontalOptions == LayoutOptions.Start`, the Popup should appear on the right side of the screen.

I've added `FlowDirection` to the `CustomSizeAndPositionPopupPage` to aid in testing.

**Comment by cat0363** [comment]
@brminnick , Thanks for adding FlowDirection to the sample.
Today, I would like to add fixes for Android, iOS, and MacCatalyst.
Unfortunately I don't have a Tizen execution environment.
Are there any specialists who are familiar with Tizen? If so, I would like to ask that person to fix Tizen.

**Comment by brminnick** [comment]
> Today, I would like to add fixes for Android, iOS, and MacCatalyst.
Amazing! Thank you @cat0363!!!

> Are there any specialists who are familiar with Tizen

Of course! @JoonghyunCho - any chance you could add the Tizen implementation to this PR once @cat0363 has completed the implementation for Windows, MacCatalyst, iOS + Android?

**Comment by cat0363** [comment]
@brminnick , It was good.
I will post it here once my corrections are complete.

**Comment by JoonghyunCho** [comment]
Tizen support is added. Looks like there is a timing issue on `FlowDirectionPopup` probably just Tizen?, I will mark on that.

Tested on Tizen IoT emulator.

**Comment by cat0363** [comment]
@JoonghyunCho , Thank you for supporting Popup's FlowDirection on Tizen.
I think it's working as expected.

**Review by brminnick — APPROVED** [review]
Another fantastic PR! Thanks @cat0363!!

**Pull request merged**
