### PR TITLE
Memory leak on TintedImageBehavior fix

### LINKED ISSUE #1612: [BUG] IconTintColorBehavior huge memory leak and app freeze on Android
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After change ImageSource, the GC clear a lot of memory. Every change cause more GC work and more app not responing time.
After 10-15 times, the app completly freeze

### Expected Behavior

After change imagesource every think still smooth work

### Steps To Reproduce

1. Open and run project from repo
2. Click buttons one by one several times (10-15 times)

### Link to public reproduction project repository

https://github.com/Marioo1357/MemoryLeakDemo

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Android
- .NET MAUI: 8
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Marioo1357**
We subscribe to OnElementPropertyChanged only once - OnAttached - instead of each time the TintColor is changed

Every time when color was applied, the void was added to event handler. It causes that every next ImageSource change, invoked heavy color logic multiple times

 ### Description of Change ###

Move dispose and subscibe logic right place in ImageTintBehavior

 ### Linked Issues ###
 

 - Fixes #1612 

 ### PR Checklist ###
 
 - [X] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [X] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

### CODE REVIEW

**Comment by Marioo1357** [comment]
> @dotnet-policy-service agree

**Comment by Marioo1357** [comment]
@dotnet-policy-service agree

**Review by VladislavAntonyuk — APPROVED** [review]
Thank you!
Just add some explanation: we subscribe to OnElementPropertyChanged only once - OnAttached - instead of each time the TintColor is changed

**Comment by Marioo1357** [comment]
PR has:
- no test because the tests on native code are not supported
- no any additional samples, because current is enough
- no documentation updated, because there is no change in any behaviour

**Pull request merged**
