### PR TITLE
Detect Shell and determine MediaElement parent

### LINKED ISSUE #1110: [BUG] MediaElement 1.0.2 crashes on iOS when exiting full screen mode and using AppShell
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using an untouched new MAUI project (using AppShell) with CommunityToolkit.MediaElement 1.0.2 from NuGet and adding a video player (MediaElement tag) it is not possible to exit full screen mode on iOS without the App crashing with the following exception:

```
ObjCRuntime.ObjCException
  Nachricht = Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x10e94dc00> should have parent view controller:<Microsoft_Maui_Controls_Platform_Compatibility_ShellSectionRootRenderer: 0x10563de00> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x1057bd2e0>
Native stack trace:
	0   CoreFoundation                      0x0000000180c63c94 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 601236
	1   libobjc.A.dylib                     0x0000000198489ee4 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180cb6e84 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 941700
	3   UIKitCore                           0x00000001833be11c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4919580
	4   UIKitCore                           0x00000001832f8334 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4109108
	5   UIKitCore                           0x00000001830b8350 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749840
	6   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	7   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	8   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	9   UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	10  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	11  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	12  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	13  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	14  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	15  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	16  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	17  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	18  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	19  UIKitCore                           0x00000001830b836c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1749868
	20  UIKitCore                           0x0000000183086604 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1545732
	21  AVKit                               0x0000000199d26874 D49827F4-890B-380B-AF26-74D929D46993 + 714868
	22  UIKitCore                           0x00000001830702c4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1454788
	23  AVKit                               0x0000000199d2596c D49827F4-890B-380B-AF26-74D929D46993 + 711020
	24  AVKit                               0x0000000199d43358 D49827F4-890B-380B-AF26-74D929D46993 + 832344
	25  UIKitCore                           0x0000000183396fd0 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 4759504
	26  UIKitCore                           0x00000001831d5500 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2917632
	27  UIKitCore                           0x00000001832480c4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3387588
	28  UIKitCore                           0x00000001832ceb84 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3939204
	29  UIKitCore                           0x0000000183172278 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2511480
	30  UIKitCore                           0x000000018379d3cc 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 8979404
	31  UIKitCore                           0x0000000183219234 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 3195444
	32  UIKitCore                           0x0000000183134764 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 2258788
	33  UIKitCore                           0x0000000183062ea4 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1400484
	34  UIKitCore                           0x0000000183063570 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1402224
	35  UIKitCore                           0x000000018306373c 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 1402684
	36  CoreFoundation                      0x0000000180c0f78c 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 255884
	37  CoreFoundation                      0x0000000180be09b4 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 63924
	38  CoreFoundation                      0x0000000180bdbf3c 309E77AA-4FF2-35B9-8AF6-33AF9C2B7929 + 44860
	39  CoreFoundation                      0x0000000180bef194 CFRunLoopRunSpecific + 572
	40  GraphicsServices                    0x00000001a1726988 GSEventRunModal + 160
	41  UIKitCore                           0x00000001833f2a88 697C7D5C-9761-36E9-8E0F-200035BF3F39 + 5134984
	42  UIKitCore                           0x000000018318bfc8 UIApplicationMain + 336
	43  VideoPlaybackTest                   0x0000000104abc5a4 xamarin_UIApplicationMain + 60
	44  VideoPlaybackTest                   0x0000000104ddc6f0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2368984
	45  VideoPlaybackTest                   0x0000000104ddb410 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2364152
	46  VideoPlaybackTest                   0x0000000104dd0dec _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2321620
	47  VideoPlaybackTest                   0x0000000104dce9c0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2312360
	48  VideoPlaybackTest                   0x0000000104d9f9c8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2119856
	49  VideoPlaybackTest                   0x0000000104cee9c0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1394856
	50  VideoPlaybackTest                   0x0000000104cf5268 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1421648
	51  VideoPlaybackTest                   0x0000000104da4bc4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2140844
	52  VideoPlaybackTest                   0x0000000104ae7528 xamarin_get_original_working_directory_path + 4016
	53  VideoPlaybackTest                   0x0000000104e0ad8c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2559092
	54  dyld                                0x00000001054984d0 start + 444

  Quelle = Microsoft.iOS
  Stapelüberwachung:
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at VideoPlaybackTest.Program.Main(String[] args) in D:\Code\test\VideoPlaybackTest\VideoPlaybackTest\Platforms\iOS\Program.cs:line 13

```

### Expected Behavior

The app should not crash when exiting full screen on iOS devices.

### Steps To Reproduce

1. Open and run the solution from the provided repository
2. Run the app on an iOS device
3. Enter and exit full screen mode of the video.

### Link to public reproduction project repository

https://github.com/blackforest-tom/maui-mediaelement-bug-102

### Environment

```markdown
- .NET MAUI CommunityToolkit.MediaElement: 1.0.2
- OS: iOS 15.7.1
- .NET MAUI: 7.0.59
```

### Anything else?

The issue is **not reproducible if you use MediaElement v1.0.1**, or if you swap out the AppShell and directly instantiate the MainPage by changing
`		MainPage = new AppShell();`
to
`		MainPage = new MainPage();`
in App.xaml.cs

### LINKED ISSUE #1214: [BUG] MediaElement crash on iOS after opening the browser if in an AppShell (iOS)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After opening a browser url inside the app, the app crash when going back to a page with a MediaElement with the error :
	NSException	{child view controller:<AVPlayerViewController: 0x7fe28b51ee00> should have parent view controller:<Microsoft_Maui_Controls_Platform_Compatibility_ShellSectionRootRenderer: 0x7fe2aaf79d80> but actual parent is:<Microsoft_Maui_Platform_PageViewController: 0x7fe2…}	Foundation.NSException

The error comes from the fixes https://github.com/CommunityToolkit/Maui/pull/1008 when using a AppShell.

### Expected Behavior

The app should not crash. It was the case in version 1.0.1.

### Steps To Reproduce

* Add a media element in a shell main page. 
* Open a Browser with Browser.OpenAsync
* Got back to the app

### Link to public reproduction project repository

https://github.com/cl3m/MediaElementShellBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0.0
- OS: iOS 16
- .NET MAUI: 7.0
```

### Anything else?

_No response_

### LINKED ISSUE #1259: [BUG] Media Element - Platform Controls Hidden on iOS 16+
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The platform controls are hidden when deploying to iOS 16+.

Using the following XAML:
```xaml
<toolkit:MediaElement Source="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                      ShouldAutoPlay="True"
                      ShouldShowPlaybackControls="True"
                      HeightRequest="300"
                      WidthRequest="400" />
```

**iOS 15.5**, when tapped the controls show:
image

**iOS 16**, when tapped the controls don't show:
image

Tapping the direct center of the video seems to work as a play/pause, but that seems to just be residue of this bug.

### Expected Behavior

The platform controls should be working in new versions of iOS.

### Steps To Reproduce

1. Add a `MediaElement` to a page:
```xaml
<toolkit:MediaElement Source="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                      ShouldAutoPlay="True"
                      ShouldShowPlaybackControls="True"
                      HeightRequest="300"
                      WidthRequest="400" />
```
2. See differences when deploying to iOS 16+ devices

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.2.0
- OS: iOS 16+
- .NET MAUI: .net 7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

It has been attempted to be fixed and written about in other issues: the parent view controller for MediaElement on iOS. This is dependant on Shell being used or not. This PR does another attempt to make it work for all scenarios.

If this works correctly, the platform controls on iOS should work on all scenarios: using Shell and on the homepage, using Shell an on a later page or not use Shell at all.

Additionally I expect this to also fix the fullscreen issue, but not 100% sure.

 ### Linked Issues ###

 - Fixes #1110
 - Fixes #1259
 - Fixes #1214

 ### PR Checklist ###

 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [X] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)

### CODE REVIEW

**Comment by RadekVyM** [comment]
Hi @jfversluis,

I also ran into issues with setting a parent view controller of the `AVPlayerViewController` recently and tried to fix them on my own. I posted my solution with some examples [here](https://github.com/RadekVyM/MauiBugs/tree/main/iOSMediaElement/iOSMediaElement).

It is probably a bit hacky solution because I have not been able to figure out in general which view controllers can and which cannot act as the parent of the `AVPlayerViewController`, but it fixes all the issues I ran into so far. I hope my solution at least helps you to find the right solution.

**Comment by alexanderdibenedetto** [comment]
@jfversluis any update here? What do you need to get this accomplished? This seems to fix the root of the issue for the Shell apps.

**Comment by VToegel** [comment]
Is there an estimate when this will be merged into the mediaelement?

**Comment by donatellijl12** [comment]
I tested this PR and it does not resolve the issue with media element inside a carousel view. 
https://github.com/dotnet/maui/issues/14417

**Pull request closed without merging**
