### PR TITLE
Added Generic EventArgs Converter

### PR DESCRIPTION
**Pull request by dnviti**
Enable users to use EventToCommandBehaviours using a generic EventArgs which casts any EventArgs inherited class. EventArgsConverter="{StaticResource Key=EventArgsConverter}"

 ### Description of Change ###

 

 ### Linked Issues ###
 

 - New Feature: https://github.com/CommunityToolkit/Maui/issues/1134

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
Hi @dnviti! I've added the `blocked` and `do not merge` tag until we've had a discussion on this new feature. 

It looks like you've skipped a few steps and opened a proposal before we've iterated over its API design in [its Discussion](https://github.com/CommunityToolkit/Maui/discussions/1133). You can find detailed information on how to add new features to `CommunityToolkit.Maui` in the [`Submitting A Feature section`in our README](https://github.com/CommunityToolkit/Maui#submitting-a-new-feature).

I'd like to see the actual API Design. You can see [previous Converter Proposals ](https://github.com/CommunityToolkit/Maui/issues/287) for examples on how to document an API design. 

I'd also like to see a real example that implements and uses this feature, showing a real use-case. The current example just demonstrates a `Command` calling `Task.Delay` and I assume our users will not be writing code like this when implementing this feature. 

Let's please move back to the [Discussion](https://github.com/CommunityToolkit/Maui/discussions/1133) to design and finalize the API and to understand the motivation and intent behind this new feature.

**Comment by brminnick** [comment]
Once the Proposal has been approved, this PR will also require Unit Tests added to `CommunityToolkit.Maui.UnitTests` and a Sample added to `CommunityToolkit.Maui.Samples`. 

We also require its documentation to be submitted to https://github.com/MicrosoftDocs/CommunityToolkit/. I recommend waiting to submit a PR to the Docs repo until the API design has been finalized to avoid any additional rework to the docs.

**Comment by pictos** [comment]
I added this on the discussion, so I'll replicate it here:

I believe we already have this implemented on EventToCommandBehavior, see:
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/event-to-command-behavior#1-use-the-generic-implementation

**Comment by brminnick** [comment]
Closing due to no response

**Pull request closed without merging**
