### PR TITLE
Dotnet format remove build

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
Error : https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=76140&view=logs&jobId=52353fe3-09c8-5f1c-434b-af3240fe8a2d

**Comment by brminnick** [comment]
Closing in favor of https://github.com/CommunityToolkit/Maui/pull/535

**Pull request closed without merging**
