### PR TITLE
Add tests, remove duplicated ColorExtensions, Microsoft.Maui.Controls

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
I see you've re-arranged the order of some modifiers (eg `readonly static` -> `static readonly`).

Is there anything we can do with `.editorconfig` or analyzers to dictate the ordering/placement of modifies like `public`, `static`, `readonly`, etc. to ensure that future PRs following this too? 

We should also update the `Contributing Code Best Practices` in our CONTRIBUTING.md: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices

**Comment by VladislavAntonyuk** [comment]
> I see you've re-arranged the order of some modifiers (eg `readonly static` -> `static readonly`).
> 
> Is there anything we can do with `.editorconfig` or analyzers to dictate the ordering/placement of modifies like `public`, `static`, `readonly`, etc. to ensure that future PRs adhere to this too?
> 
> We should also update the `Contributing Code Best Practices` in our CONTRIBUTING.md: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices

Visual Studio suggested me it, I think it is already a part of editorconfig

**Comment by brminnick** [comment]
> I think it is already a part of editorconfig

Nice! Could we elevate it from a suggestion to an error like we did with `nullable`?

**Comment by VladislavAntonyuk** [comment]
> > I think it is already a part of editorconfig
> 
> Nice! Could we elevate it from a suggestion to an error like we did with `nullable`?

Sure, done

**Review by brminnick — APPROVED** [review]
Thanks Vlad! 

I hadn't seen the other workloads like `<UseMauiCore>true</UseMauiCore>`.

It's perfect for `CommunityToolkit.Maui.Core` 💯 

https://github.com/dotnet/maui/blob/56906b01d8ce5b3c9d36919b60a26d938c497426/src/Workload/README.md

**Comment by VladislavAntonyuk** [comment]
> Thanks Vlad! 
> 
> 
> 
> I hadn't seen the other workloads like `<UseMauiCore>true</UseMauiCore>`.
> 
> 
> 
> It's perfect for `CommunityToolkit.Maui.Core` 💯 
> 
> 
> 
> Here's the link to all of the available workloads for anyone else who hdsn't seen it like me!
> 
> https://github.com/dotnet/maui/blob/56906b01d8ce5b3c9d36919b60a26d938c497426/src/Workload/README.md

I've just read the latest release notes 😃

**Pull request merged**
