### PR TITLE
Test runner ci

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by pictos** [comment]
Why not use the PR that I already opened?

**Comment by VladislavAntonyuk** [comment]
@pictos I will use your PR, but CI runs on main only

**Comment by pictos** [comment]
@VladislavAntonyuk my question was more, why you didn't use my PR to perform this work? The software part is done, just the CI is missing. But if you feel this a better option, let's go baby

**Comment by VladislavAntonyuk** [comment]
@pictos feel free to approve/merge the pr if you accept the changes

**Review by pictos — APPROVED** [review]

**Pull request merged**
