### PR TITLE
Add Popup Support for MediaElement on iOS + MacCatalyst

### LINKED ISSUE #2246: [BUG] iOS MediaElement Crashes When in Popup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When opening a `Popup` that contains `MediaElement`, the app crashes with the following Exception:

```
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: child view controller:<AVPlayerViewController: 0x1617b7000> should have parent view controller:<Microsoft_Maui_Platform_PageViewController: 0x16fb51780> but actual parent is:<Microsoft_Maui_Controls_Platform_Compatibility_ShellFlyoutRenderer: 0x107458fd0>
```

### Expected Behavior

The Popup should display the MediaElement

### Steps To Reproduce

1. On an iOS device, launch `CommunityToolkit.Maui.Sample`
2. In `CommunityToolkit.Maui.Sample`, navigate to Views -> MediaElement
3. Tap on `Popup`
4. Confirm app crashes

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples

### Environment

```markdown
- .NET MAUI CommunityToolkit: CommunityTooklit.Maui.MediaElement v4.1.1
- OS: iOS 18
- .NET MAUI: 


 [maui]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.82/WorkloadManifest.json
   Install Type:        FileBased
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by brminnick**
### Description of Change ###

This PR traverses the MediaElement visual tree on iOS to see if it is being used by any control whose `Parent.Handler.PlatformView` is `UIViewController`. 

If we do find a `UIViewController`, we add it as a child `ViewController` to `class MauiMediaElement : UIView`.

 ### Linked Issues ###
 

 - Fixes #2246 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)

 ### Additional information ###

This PR adds support for Popup which was broken by PR https://github.com/CommunityToolkit/Maui/pull/2245

### CODE REVIEW

**Comment by brminnick** [comment]
Hhere's a screenshot of MediaElement playing inside a Popup in `CommunityToolkit.Maui.Sample`

image

**Review by ne0rrmatrix — APPROVED** [review]
Looks good. If you can tap outside popup and open it a second time without issues I would say this PR is GTG

**Comment by brminnick** [comment]
> Looks good. If you can tap outside popup and open it a second time without issues I would say this PR is GTG

Excellent! I confirmed that we're good to go 🚀

ezgif-6-06fa368e3b

**Comment by ne0rrmatrix** [comment]
Setting full screen while in popup and then going back to normal causes crash on IOS 18.x running xcode 16.x

**Comment by ne0rrmatrix** [comment]
9F1D8AB0-4EB8-44F1-9CFD-4D9F605DD087

**Comment by brminnick** [comment]
Good catch, @ne0rrmatrix. Could you please open a new Issue for this to ensure we don't lose track of this bug?

**Pull request merged**
