### PR TITLE
.NET 8

### LINKED ISSUE #1284: [Proposal] .Net 8 Preview (Beta) Nuget
### Feature name

.Net 8 Preview (Beta) Nuget

### Link to discussion

https://github.com/CommunityToolkit/Maui/issues/1243

### Progress tracker

- [X] Android Implementation
- [X] iOS Implementation
- [X] MacCatalyst Implementation
- [X] Windows Implementation
- [X] Tizen Implementation
- [ ] Unit Tests
- [ ] Samples
- [ ] Documentation

### Summary

Create a .Net 8 Preview version as a beta nuget. So not the official nuget that people are forced to use, but just a beta nuget that people can optionally upgrade to if they have decided to start using .Net 8 Preview.

### Motivation

A lot of bug fixes are being rolled out for .Net 8 Preview versions of Maui; at this point, the .Net 8 preview is as stable as the .Net 7 (7.0.86) version. 

A beta Nuget will not notify people that they should update to the new version, and will keep the stable .Net 7 version as the official Nuget. But it will allow people who are preparing for .Net 8  to start developing and test for bug in preparation for its official launch. Currently, if you reference the 5.2.0 CommunityToolkit Nuget, it will throw a TypeLoadException on startup. 

### Detailed Design

na

### Usage Syntax

```markdown
Reference .Net 8 Preview5.8529
```

### Drawbacks

The only reason for not preparing for .Net 8 is that it takes extra time to create a new Nuget. 

### Alternatives

_No response_

### Unresolved Questions

_No response_

### LINKED ISSUE #1460: [BUG] Snackbar InvalidOperationException when using dotnet trimmer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When attempting to show a `Snackbar` on a Maui app for Android with dotnet trimmer `full` mode enabled, the following exception occurs:
```
System.InvalidOperationException: Unable to find Snackbar text view
  at CommunityToolkit.Maui.Alerts.Snackbar.SetMessageForView(View&, IFontManager)
  at CommunityToolkit.Maui.Alerts.Snackbar.ShowPlatform(CancellationToken )
  at MauiAppSnackbar.MainPage.OnCounterClicked(Object sender, EventArgs e)
```

### Expected Behavior

Instead of throwing an exception, the `Snackbar` should be displayed.

Workaround: do not trim CommunityToolkit.Maui
```
<ItemGroup Condition="'$(Configuration)|$([MSBuild]::GetTargetPlatformIdentifier($(TargetFramework)))'=='Release|android'">
	<TrimmerRootAssembly Include="CommunityToolkit.Maui" RootMode="All" />
</ItemGroup>
```

### Steps To Reproduce

1. Open the repro project
2. Launch in release mode (dotnet trimmer full mode)
3. Click on button: a dialog will appear, catching the exception that is raised by CommunityToolkit.Maui

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppSnackbar

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0
- OS: Android
- .NET MAUI: 8.0 rc2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #1284 
 - Fixes  #1460

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
@VladislavAntonyuk FYI - the PR we merged today introduced merge conflicts in the `csproj` files on this PR

**Comment by brminnick** [comment]
I wonder if we can also remove our reference to the `DotNet.ReproducibleBuilds` NuGet package now that SourceLink is included in .NET 8: https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#source-link?

I haven't tried it yet with the toolkit, but it's certainly something we can look into!

**Comment by VladislavAntonyuk** [comment]
> I wonder if we can also remove our reference to the `DotNet.ReproducibleBuilds` NuGet package now that SourceLink is included in .NET 8: [learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#source-link](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#source-link)?
> 
> I haven't tried it yet with the toolkit, but it's certainly something we can look into!

removed, let's see how it works. we can always add it if necessary

**Comment by brminnick** [comment]
Update: @CliffAgius is going to update our documentation on how to consume our preview packages so that community members can use this .NET 8 pre-release of `CommunityToolkit.Maui`:
1. Update the [Wiki](https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages)
2. Add documentation to the Official Docs: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/

**Comment by inforithmics** [comment]
Any plans to include this

https://github.com/CommunityToolkit/Maui/pull/1342#issuecomment-1676301789

.Net Maui has now the possibility to AddLogicalChilderen instead of only Setting the Parent.

**Comment by ne0rrmatrix** [comment]
On IOS the player position is not being reported. Works fine on Android and Windows.

**Comment by ne0rrmatrix** [comment]
What is the best practices for reporting issues with this PR? I am having issues with differences in behavior between devices? Should I even mention it? The official samples work as expected when I test the feature I am having issues with. Should I even be commenting with bugs? Or should I wait till its released?

**Review by brminnick — APPROVED** [review]
Thanks Vlad!!

**Comment by brminnick** [comment]
Thanks @ne0rrmatrix!  

Now that we've merged our PR supporting .NET 8, could you test MediaElement again on the `main` branch and then open an Issue if you confirm the bug still exists?

**Comment by ne0rrmatrix** [comment]
I tested my use case against main. I am having issues on Android and IOS. Untested on Mac atm.  I don't believe the issue is caused by media element itself though. The sample builds fine and works as expected. 

I am having issues with being unable to get the position of playback while playing any media. I can get the duration just fine.  I am using a content view and have created custom controls. The content view is unable to get the position. It works fine in dotnet 7.x app but as soon as I switch to 8.x it stops working. This does not appear to be an issue for windows at all. It is just mobile devices like android or IOS. Have not tested on mac. It only affects me when using a content view. Directly using media element everything works as expected. 

The issue is most likely not directly related to the toolkit. It appears to be an issue with either my code implementation of binding or a bug in Maui itself. I will have to do further testing to figure out where it is the problem originates.

**Pull request merged**
