### PR TITLE
Corrected the xmlns typo

### LINKED ISSUE #264: [Bug] Xmlns includes a typo
### Description

As discussed in part of the proposal at #245 it has been discovered that there is a typo in the xmlns definition. Raising this issue as the changes have made it out in to a release.

### Link to Reproduction Sample

N/A

### Expected Behavior

`xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"`

### Actual Behavior

`xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/tookit"`

Note the missing l on toolkit

### Basic Information

- Version with issue: `1.0.0-pre5`
- Last known good version: N/A
- IDE: 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: `CommunityToolkit.Maui`
- Affected Devices:

### PR DESCRIPTION
**Pull request by bijington**
### Description of Change ###

 

This PR corrects a typo in the xmlns definition added.

`tookit` becomes `toolkit`

 ### Linked Issues ###
 

 - Fixes #264

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by bijington** [comment]
The typo has been fixed and there is currently some discussion around introducing an `XmlnsPrefix`. It is considered good practice to include it even it is matches the current default.

There are current questions over whether `toolkit` is too long. I quite like it but I appreciate there isn't much context on which toolkit is being used. Some options are:

`toolkit` - current

`mct` - MAUI Community Toolkit

`ctm` - CommunityToolkit.Maui

**Comment by VladislavAntonyuk** [comment]
I like mct. I think it is unique, so we unlikely have correlation with possible different toolkits

**Comment by egvijayanand** [comment]
My suggestion would also be to go with `mct` as it sounds similar to the existing `xct` package and .NET MAUI itself is an evolution of Xamarin.Forms and many existing developers would feel at home.

Regards,
Vijay Anand E G

**Comment by bijington** [comment]
I agree to liking `mct` also

**Comment by bijington** [comment]
To the reviewer, I haven't been able to test the code action use of the new `mct` `XmlnsPrefix` as Visual Studio on my machine is refusing to offer any suggestions in XAML right now.

**Comment by pictos** [comment]
@bijington I can try on my end. What's the expected behavior for `XmlnsPrefix`?

**Comment by bijington** [comment]
> @bijington I can try on my end. What's the expected behavior for `XmlnsPrefix`?

Great thank you. I expect that if you add something from the toolkit in XAML then the code action fix will add the namespace to the root of the element and it would set this:

`xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"`

Where it used to set:

`xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"`

**Comment by pictos** [comment]
Looks like the intellisense isn't working for me as well. Should be a xaml editor bug

**Comment by bijington** [comment]
> Looks like the intellisense isn't working for me as well. Should be a xaml editor bug

😭

**Comment by bijington** [comment]
Still short of testing how the prefix attribute works works I believe this change is ready

**Review by brminnick — APPROVED** [review]

**Pull request merged**
