### PR TITLE
iOS popup fix with Shell or TabbedPage

### PR DESCRIPTION
**Pull request by cucumber-sp**
### Linked Issues ###
#822 
#992 

 - Fixes #
These issues are closed but it still happens if you have Shell or TabbedPage because they're returning true to `page.IsPlatformEnabled` even if child page is not loaded. Instead of checking `page.IsPlatformEnabled` or/and subscribing to it's navigation events, get child page (if it exists) and use it.

 ### PR Checklist ###
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [x] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###
I tested it on iOS with OnAppearing method inside VM (`Application.Current.MainPage.ShowPopupAsync()`) which returns Shell, so it crashes. It can be avoided by using `Application.Current.MainPage.GetCurrentPage().ShowPopupAsync()` but it might be unclear for some users, so i think it should be checked before trying to display popup for page.

### CODE REVIEW

**Comment by pictos** [comment]
You referenced closed/fixed issues... Did you or we missed something?

**Review by brminnick — APPROVED** [review]
Thanks @cucumber-sp!

**Comment by pictos** [comment]
Reading the updated description provided by @cucumber-sp , this looks like a bug on .NET MAUI side and his fix works around the issue and doesn't fix it. The popup should use the page provided by the parameter, since that page is the Page that the user will ask the popup to show up, With this change we break it. Now, no matter what, the popup will not be attached to the required Page but by some CurrentPage provided by the system.

**Comment by cucumber-sp** [comment]
@pictos nope, you're wrong here. You could check platform-specific code for popups and you will see that it used the same `.GetCurrentPage()` method while presenting popup. I just moved this thing before `page.IsPlatformEnabled` check so it won't crash if parent page is loaded, but child is not.

**Comment by pictos** [comment]
@cucumber-sp the only platform-specific that has that call is on Windows, and it's because of the way that platform handles it. On others, this should be needed. And the situation that you described should be fixed by #934, since it closes your referenced issues. The correct approach was to create an issue and provide a sample code to investigate the issue.

This PR changes the meaning of the code... So, let's say that you call.

`await MyTabbedPage.ShowPopupAsync(aboutPopup);`

Now with your change, the popup will not be created in the context of the TabbedPage, but will be created in the context of the presented page (a child of the TabPage) and that's not how it was designed to work, it could introduce new bugs and for sure it's a breaking change/

**Comment by cucumber-sp** [comment]
@pictos wrong again, it already did this before (https://github.com/cucumber-sp/CommunityToolkit.Maui/blob/4fbf6a8a64dbed252ab4866f87410b01605cf964/src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs#L90). The only thing I did is checking if page is loaded for final page, not the given one.

**Comment by pictos** [comment]
you did what? Your change was just in one method... The line that you pointed out is what I did. You didn't check if the Page is loaded, you grabbed the currentPage. But since I'm wrong, can you educate me how that method works?

**Pull request merged**
