### PR TITLE
FIX: AvatarView clipping on Android isn't applied correctly

### LINKED ISSUE #646: [BUG] AvatarView clipping on Android isn't applied correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I updated to latest version yesterday and this issue appeared, when I use toolkit AvatarView

image

image

### Expected Behavior

before update the AvatarView control was working well as I expected .. the circle image showing well without black borders or black background as I show you in Current Behavior section in images. 

### Steps To Reproduce

1. Add an **AvatarView** control.
2. Set as the **ImageSource** a Uri as image.

### Link to public reproduction project repository

https://github.com/GeorgeLeithead/CommunityToolkitMaui/tree/510-Bug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.2.0
- OS: Windows 10 Build 10.0.19041.0
- .NET MAUI: 6.0.408
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by GeorgeLeithead**
### Description of Change ###
Added clipping offset for all platforms, other than Windows.

 ### Linked Issues ###
 - Fixes #646 

 ### PR Checklist ###
 - [X] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [X] Has tests (if omitted, state reason in description) : N/A
 - [X] Has samples (if omitted, state reason in description): N/A
 - [X] Rebased on top of `main` at time of PR
 - [X] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [X] Documentation created or updated: N/A

 ### Additional information ###
Tested and verified on platforms - 
- [X] Android
- [X] Windows
- [x] Mac Catalyst
- [x] iOS

This fix must be tested on **ALL** platforms, as it is an issue for different platforms.

### CODE REVIEW

**Comment by GeorgeLeithead** [comment]
I am unable to verify if this bug exists on the iOS or Mac Catalyst platform.  As such, I need someone else to verify and if appropriate update the pre-processor directive.

**Comment by brminnick** [comment]
Thanks George! I tested on iOS + MacCatalyst and everything looks good,

If you are finished working on this PR, please change it from `Draft` to `Ready for Review` and we will merge it in 🙌

**Review by brminnick — APPROVED** [review]

**Review by brminnick — APPROVED** [review]

**Pull request merged**
