### PR TITLE
Use culture when convert colors

### LINKED ISSUE #553: [Bug] ColorConverters don't use current culture info
### Description

We should use the culture info when we convert color with alpha to string.

for example:
alpha: 0.5.
ToString() in US it returns 0.5
ToString() in UA it return 0,5

As a result, all color tests failed on my machine.

### Steps to Reproduce

1. Create color Color(0, 0, 0, 0.5f); with alpha
2. Call converter with culureInfo: converter.Convert(color, new CultureInfo("en-US");

### Expected Behavior
Use culture info to set the correct delimiter.
UA: CMYKA(0%,0%,0%,100%,_**0.5**_)
US: CMYKA(0%,0%,0%,100%,_**0.5**_)

### Actual Behavior
culture info is ignored
UA: CMYKA(0%,0%,0%,100%,_**0,5**_)
US: CMYKA(0%,0%,0%,100%,_**0.5**_)

### Basic Information

- Version with issue: 1.2.0

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Fixes 
- Fixes #553

 ### Description of Change ###

Use culture info to set the correct delimiter.

 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [x] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/134 

 ### Additional information ###

### CODE REVIEW

**Comment by pictos** [comment]
@VladislavAntonyuk what's the issue? I couldn't figure out what this PR solves

**Comment by VladislavAntonyuk** [comment]
When we convert color with alpha to string we should use the culture info.

for example:
alpha: 0.5.
ToString() in US it returns 0.5
ToString() in UA it return 0,5

As a result all color tests are failed on my machine.

**Comment by pictos** [comment]
got it, can you open an issue reporting this later? Just to keep track

**Comment by VladislavAntonyuk** [comment]
https://github.com/CommunityToolkit/Maui/issues/553

**Review by pictos — APPROVED** [review]

**Review by brminnick — APPROVED** [review]

**Comment by brminnick** [comment]
Merging this in preparation for our next release.

We'll merge the Docs PR on release day 👍

**Pull request merged**
