### PR TITLE
Fix MediaElement CTD on Windows

### LINKED ISSUE #2143: [BUG] MediaElement Android .NET8 crashing
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have created a new Maui project. Added Community Toolkit and Community Toolkit MediaElement (following https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=android#clean-up-mediaelement-resources)

Created a new page (Test.xaml) with the mediaElement. When the media element is started or stopped the following error is causing an exception:

`MediaManager: Error: AndroidX.LocalBroadcastManager.Content.LocalBroadcastManager not supported on Android 13 and above.`

Added clean up from same link above:
```
...
Unloaded="ContentPage_Unloaded">
```

```
  void ContentPage_Unloaded(object? sender, EventArgs e)
  {
      // Stop and cleanup MediaElement when we navigate away
      mediaElement.Handler?.DisconnectHandler();
  }
```
This causes the entire app to crash with exception:
```
Information: 0 : 
MediaControlsService destroyed.
The program 'xxxxx.MAUI.dll' has exited with code 0 (0x0).
```

### Expected Behavior

Well, just being able to play and stop video and also leaving the page without the app to cause exceptions and crash.

### Steps To Reproduce

1. Open and run solution.
2. Click button AAA.
3. Start/stop and/or press back button.

### Link to public reproduction project repository

https://github.com/KasperSommer/MediaElementIssue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- .NET MAUI CommunityToolkit.Maui.MediaElement: 4.1.0
- OS: Android 34
- .NET MAUI: net8.0-android
```

### Anything else?

I have mentioned it here as well: https://stackoverflow.com/questions/78894331/maui-community-toolkit-mediaelement-crashing?noredirect=1#comment139101057_78894331

I really hope I have done this correctly :)

### PR DESCRIPTION
**Pull request by ne0rrmatrix**
- Bug fix

 ### Description of Change ###

- Updated `UpdateMetadata` in `MediaManager.windows.cs` to return early if `MediaElement.MetadataArtworkUrl` is null or empty.
- Added tests in `MediaElementTests.cs`:
  - `PosterIsNotStringEmptyorNull`: Verifies `MetadataArtworkUrl` is not null or empty when set to a valid URL.
  - `PosterIsStringEmptyDoesNotThrow`: Ensures no exceptions when `MetadataArtworkUrl` is an empty string and correctly identifies it as empty.
  - 
 ### Linked Issues ###
 - Fixes

 ### PR Checklist ###

 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###
Fixes a nasty bug where App crashes when you do not set artwork for media element. When setting poster we cannot set it to string empty. That is what is crashing windows. Added `string.IsNullOrEmpty` check to `MediaElement.MetadataArtworkUrl` so that we do not set the poster if it is not present.

### CODE REVIEW

**Review by brminnick — APPROVED** [review]
Thanks James! Just FYI - I implemented `Uri.TryCreate` to verify the url. 

I also added a quick async/await fix that will improve performance as well.

**Comment by brminnick** [comment]
@ne0rrmatrix - could you double check that the correct Issue is linked to this PR? 

The Issue that is currently linked (https://github.com/CommunityToolkit/Maui/issues/2143) is specifically focusing on Android, while this PR is only focusing on Windows.

**Comment by ne0rrmatrix** [comment]
@brminnick Yes I see that is android now. I did not even test that. I just tested windows. I will create a bug report for that then.

**Comment by ne0rrmatrix** [comment]
I removed the linked issue

**Pull request merged**
