### PR TITLE
fix: Fix unhandled ObjectDisposedException in IconTintColorBehavior.ClearTintColor on Android

### LINKED ISSUE #1819: [BUG] IconTintColorBehavior crash on android.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

IconTintColorBehavior crash while changing tint color.

System.ObjectDisposedException: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, AndroidX.AppCompat.Widget.AppCompatImageView
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Android.Widget.ImageView.SetColorFilter(ColorFilter )
   at CommunityToolkit.Maui.Behaviors.IconTintColorBehavior.<ApplyTintColor>g__SetImageViewTintColor|2_0(ImageView image, Color color)

### Expected Behavior

IconTintColorBehavior does not crash. 

### Steps To Reproduce

Unfortunately, I have some nuget problems with adding package, but you should be able to reproduce it by changing tint color.

### Link to public reproduction project repository

no link currently

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

### Anything else?

I found fix for this. Just remove PropertyChanged event handler in OnDetachedFrom method. In previous version handler is added, but not removed.

public partial class WorkaroundTintedImageBehavior
{
    private View? _bindable;
    private AView? _platformView;
    
    protected override void OnAttachedTo(View bindable, AView platformView)
    {
        _bindable = bindable;
        _platformView = platformView;
        
        bindable.PropertyChanged += OnElementPropertyChanged;
        ApplyTintColor(platformView);
        PropertyChanged += OnTintedImagePropertyChanged;
    }

    protected override void OnDetachedFrom(View bindable, AView platformView)
    {
        ClearTintColor(bindable, platformView);
        bindable.PropertyChanged -= OnElementPropertyChanged;
        PropertyChanged -= OnTintedImagePropertyChanged;
    }

    private void OnTintedImagePropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == TintColorProperty.PropertyName && _bindable is not null && _platformView is not null)
        {
            ApplyTintColor(_platformView);
        }
    }

    private void ApplyTintColor(AView control)
    {
        var color = TintColor;

        switch (control)
        {
            case ImageView image:
                SetImageViewTintColor(image, color);
                break;
            case AButton button:
                SetButtonTintColor(button, color);
                break;
            default:
                throw new NotSupportedException($"{nameof(WorkaroundTintedImageBehavior)} only currently supports Android.Widget.Button and {nameof(ImageView)}.");
        }

        static void SetImageViewTintColor(ImageView image, Color? color)
        {
            if (color is null)
            {
                image.ClearColorFilter();
                return;
            }

            image.SetColorFilter(new PorterDuffColorFilter(color.ToPlatform(), PorterDuff.Mode.SrcIn ?? throw new InvalidOperationException("PorterDuff.Mode.SrcIn should not be null at runtime.")));
        }

        static void SetButtonTintColor(AButton button, Color? color)
        {
            var drawables = button.GetCompoundDrawables().Where(d => d is not null);

            if (color is null)
            {
                foreach (var img in drawables)
                {
                    img.ClearColorFilter();
                }

                color = Colors.Transparent;
            }

            foreach (var img in drawables)
            {
                img.SetTint(color.ToPlatform());
            }
        }
    }

    private void OnElementPropertyChanged(object? sender, PropertyChangedEventArgs args)
    {
        if (args.PropertyName is not string propertyName
            || sender is not View bindable
            || bindable.Handler?.PlatformView is not AView platformView)
        {
            return;
        }

        if (!propertyName.Equals(Image.SourceProperty.PropertyName, StringComparison.Ordinal)
            && !propertyName.Equals(ImageButton.SourceProperty.PropertyName, StringComparison.Ordinal))
        {
            return;
        }

        ApplyTintColor(platformView);
    }

    private void ClearTintColor(View element, AView control)
    {
        element.PropertyChanged -= OnElementPropertyChanged;
        switch (control)
        {
            case ImageView image:
                image.ClearColorFilter();
                break;
            case AButton button:
                foreach (var drawable in button.GetCompoundDrawables())
                {
                    drawable?.ClearColorFilter();
                }

                break;
        }
    }
}

### PR DESCRIPTION
**Pull request by Kay-STL**
### Description of Change ###
Following #1883, which fixed an ObjectDisposedException crash in `ApplyTintColor`, this PR fixes a crash in `ClearTintColor` in the same manner. Other users have reported experiencing this in the replies to the original issue linked below.
 

 ### Linked Issues ###
 

 - Fixes #1819 

 ### PR Checklist ###
 
 - [X] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [X] Rebased on top of `main` at time of PR
 - [X] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###
Android only. Reproduced reliably in a production application on an Android 11 device, cannot reproduce after patch is applied.

### CODE REVIEW

**Comment by Kay-STL** [comment]
@dotnet-policy-service agree company="Swallowing Technologies Limited"

**Review by ScottyLightnin — APPROVED** [review]

**Comment by brminnick** [comment]
@Kay-STL Could you update this PR to allow maintainers to edit it? I'd like to merge it but I first need to fix the merge conflict.

image


https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Kay-STL** [comment]
@brminnick Can't enable maintainer access since GitHub doesn't allow it on organization repos, sorry - I've fixed the conflicts, will make sure to PR from a personal repo next time :)

**Review by brminnick — APPROVED** [review]

**Comment by christian-strydom** [comment]
Thank you so much for this fix! This solved the last of my icon tint crashes.

**Pull request merged**
