### PR TITLE
Use font in Snackbar

### LINKED ISSUE #1033: [BUG] Missing Right Padding and Custom Font not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

All the platforms.
Font Icons are not displayed in the snack bar.

iOS & MacCatalyst
Missing Padding at the right side of the snack bar when a string is set in the ActionButtonText.

### Expected Behavior

All the platforms.
Use the correct Font provided by the SnackbarOption.

iOS & MacCatalyst
Include the right padding in the Snackbar.

### Steps To Reproduce

1. Open and run the solution from the reproduction repository
2. Click the button and observe the bug.

Screenshot 2023-02-24 at 21 34 10

### Link to public reproduction project repository

https://github.com/JosueDM94/MauiSnackbarBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: 
       * Android All Version
       * iOS All Version
       * MacCatayst All Version
- .NET MAUI: 7.0.59
```

### Anything else?

Thanks in advance for this AMAZING library!

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #1033 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by pictos** [comment]
Instead of adding this huge [file](https://github.com/CommunityToolkit/Maui/blob/730e4085679609e2de76253cfc5a77f939447bf6/samples/CommunityToolkit.Maui.Sample/Resources/Fonts/FontAwesomeIcons.cs), can we just have the csharp version for icons that are used in the sample?

**Review by brminnick — CHANGES_REQUESTED** [review]
Screenshot 2023-02-26 at 12 50 02 PM
Thanks Vlad! It looks like the Microsoft logo is showing up properly on macOS.

I confirmed it is working on iOS + Android.

**Comment by VladislavAntonyuk** [comment]
that's interesting. we have the same code for ios and macos. seems like font manager is null or font is not correctly resolved.

**Comment by brminnick** [comment]
> that's interesting. we have the same code for ios and macos. seems like font manager is null or font is not correctly resolved.

I'm not a Maccatalyst expert, but it may just require different APIs than iOS. 

This could also be a .NET MAUI bug. If it is, let's open an Issue on the repo, link to it here and include a note in our docs.

**Comment by VladislavAntonyuk** [comment]
yep. I will investigate it tomorrow.

**Comment by VladislavAntonyuk** [comment]
@brminnick it seems like it works. just. need to rebuild the application:
image

**Review by brminnick — APPROVED** [review]

**Comment by VladislavAntonyuk** [comment]
give me a second to double-check it again

**Comment by VladislavAntonyuk** [comment]
@brminnick actually there was an issue. either padding or font awesome was applied. fixed

**Review by brminnick — APPROVED** [review]

**Pull request merged**
