### PR TITLE
Fix failing test on Pipelines. Test only fails on Pipelines.

### PR DESCRIPTION
**Pull request by ne0rrmatrix**
- Bug fix
 ### Description of Change ###

Fix failing test on Azure pipelines. it fails about 8 percent of the time. It has zero percent failure on my local machines. Passes on Mac mini and two different windows PC's. I have no idea why it only fails a small percentage of the time and only on Azure pipelines.

 ### PR Checklist ###

 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by GeorgeLeithead** [comment]
Just to document against the PR.  According to the xUnit.net documentation [Configuration Files](https://xunit.net/docs/configuration-files), the test project needs to copy the `xunit.runner.json` file to the build output directory for it to be used by the test runner, which it looks like we were not doing.  Therefore we do not believe that the Azure test runner was abiding by out configuration and instead using defaults.

**Comment by brminnick** [comment]
Thanks James!! I hope this does the trick!

It's been super annoying having to manually re-run our pipeline each time 😅

**Comment by GeorgeLeithead** [comment]
We had a great community effort on the Discord server, lead by James @ne0rrmatrix.

**Pull request merged**
