### PR TITLE
Fix background issue on apple platform

### LINKED ISSUE #450: [Bug] Popup color issues on iOS
### Description
Reporting three issues here:
1. I set the `color` of the popup but it completely disregards it and goes with the color of theme on device
2. I open the popup from the view model of a page with white background. When I close the popup, the background of page changes to the color of theme on device.
3. Popup also seems to ignore position settings on iOS

Please note that popup behaves exactly the way it should on Android but not on iOS.

I'm testing this on an iPhone Xs with theme set to dark. I, however, wanted my app to have a white background so I manually set the `BackgroundColor="White"` on the page and `Color="White"` on the popup.

When the popup opens up, its background is black even though I set it to white. Once I close the popup by clicking the button, it closes but the background color of my page also becomes black. Here are the screen shots in sequence. Notice the background of the page has already turned black once the popup opens up.

As mentioned, I specifically set page background to white  and set the background of popup to white as well using code below:

```
<?xml version="1.0" encoding="utf-8" ?>
<mct:Popup xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
           xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
           xmlns:vm="clr-namespace:Ingrid.Connect.ViewModels.Personal"
           x:Class="Ingrid.Connect.Views.Personal.ConfirmCouponSubmission"
           x:DataType="vm:ConfirmCouponSubmissionViewModel"
           Color="{StaticResource White}"
           HorizontalOptions="Center"
           VerticalOptions="Center"
           Size="250,250">
</mct:Popup>
```

- Version with issue: CommunityToolkit.Maui 1.0.0
- IDE: Visual Studio 2022 17.3.0 Preview 1.1
- Platform Target Frameworks: 
  - iOS:  10
  - Android: 21
- Nuget Packages: CommunityToolkit.Maui, CommunityToolkit.Mvvm, Plugin.InApp, MonkeyCache.FileStore, sqlite-net-pcl
- Affected Devices: iPhone Xx

### Workaround
No workaround that I'm aware of.

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

Make sure to change the correct backgroundColor View on Apple platform. And make sure to call the `SetBackgroundColor` when the `View` isn't `null`.

 ### Linked Issues ###
 

 - Fixes #450

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

 
 
Screen Shot 2022-06-10 at 15 32 29

### CODE REVIEW

**Comment by pictos** [comment]
@brminnick can you take a look at the build error? It happened after your commit to the `main` branch

**Comment by brminnick** [comment]
Oh goodness! So sorry about that - I thought I was working on a branch!

Thanks for letting me know! I've reverted those commits to `main`.

**Comment by pictos** [comment]
@brminnick you coolest than me, because I can't push to `main`, and I tried more than once xD

**Review by brminnick — APPROVED** [review]
Thanks Pedro!

**Pull request merged**
