### PR TITLE
Update ColorToStringConverter.shared.cs

### PR DESCRIPTION
**Pull request by cl2raul66**
Add ColorToHexArgbStringConverter
 
This PR adds a new converter, ColorToHexArgbStringConverter, which allows you to convert between Color objects and hex strings in ARGB format.

### CODE REVIEW

**Comment by cl2raul66** [comment]
@dotnet-policy-service agree

**Comment by brminnick** [comment]
Thanks! Before we can merge this, we need two more things:

- [ ] Add Unit Tests 
- [ ] Write Documentation: 
  - Please submit a PR to the Docs repo: https://github.com/MicrosoftDocs/CommunityToolkit/tree/main/docs/maui/converters
  - You can leverage the existing `ColorToHexRgbaStringConverter` docs to write your documentation: https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/color-to-hex-rgba-string-converter.md

**Comment by cl2raul66** [comment]
> * Add Unit Tests

 I don't know how to do that step

**Comment by Jake-Derrick** [comment]
@cl2raul66, I created a [PR to add unit tests](https://github.com/cl2raul66/Maui/pull/1) to this branch. Let me know what you think!

**Comment by brminnick** [comment]
Thanks @Jake-Derrick!

@cl2raul66 - could you please merge it? I believe you're the only one who has the capability to accept + merge his PR.

**Comment by brminnick** [comment]
Thanks! I approve this PR.

Once you've opened a PR on our Docs Repo providing documentation of the new feature, we can merge this.

> - [ ] Write Documentation: 
>   - Please submit a PR to the Docs repo: https://github.com/MicrosoftDocs/CommunityToolkit/tree/main/docs/maui/converters
>  - You can leverage the existing `ColorToHexRgbaStringConverter` docs to write your documentation: https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/color-to-hex-rgba-string-converter.md

**Comment by bijington** [comment]
Docs PR is in, sorry we missed this: https://github.com/MicrosoftDocs/CommunityToolkit/pull/451

**Review by bijington — APPROVED** [review]

**Pull request merged**
