### PR TITLE
Make test sdk match the test runner on the Mac build agent

### PR DESCRIPTION
**Pull request by bijington**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
Interesting! Do you think this may be the cause of why our Unit Tests randomly fail in the CI/CD pipeline?

**Comment by bijington** [comment]
> Interesting! Do you think this may be the cause of why our Unit Tests randomly fail in the CI/CD pipeline?

It's probably nothing but I noticed that the macOS agent is running:

> Microsoft (R) Test Execution Command Line Tool Version 17.10.0 (x64)

**Review by brminnick — APPROVED** [review]
So far so good!

**Comment by bijington** [comment]
3 successful builds in a row. Fingers crossed it stays that way

**Comment by bijington** [comment]
Looks like it wasn't this

**Pull request merged**
