### PR TITLE
Fixed auto-generated flag in Generated code

### LINKED ISSUE #411: [Bug] Extention method TextColorTo() generates warnings
### Description

The TextColorTo extention methods are being created via SourceGenerators. These source generators however create CS0436 warnings when the CommunityToolkit is used in a library. 

C:\Users\R\source\repos\CommunityToolkitSample\CommunityToolkitSample.App\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo_71aacac4-5ef7-473e-aae1-1fe5429261f1.g.shared.cs(41,89,41,119): warning CS0436: The type 'ColorAnimationExtensions_Label' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo_71aacac4-5ef7-473e-aae1-1fe5429261f1.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Label' in 'CommunityToolkitSample.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo_71aacac4-5ef7-473e-aae1-1fe5429261f1.g.shared.cs'.

### Link to Reproduction Sample

https://github.com/RichardMarsh/CommunityToolkitSample

### Steps to Reproduce

1. Create a .NET MAUI Library that references the CommunityToolkit
2. Create a .NET MAUI app that references the library created in step 1
3. Build

### Basic Information

- Version with issue: 1.0.0-rc3
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 21.0

### Workaround
Remove the analyzer from the custom library project. However that means the custom library does not have access to those features.

`
<Target Name="DisableAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
        <Analyzer Remove="@(Analyzer)" Condition="'%(Filename)' == 'CommunityToolkit.Maui.SourceGenerators'" />
    </ItemGroup>
</Target>
`

### LINKED ISSUE #527: [Bug] Analyzers don't like our SG code style
For more info, see #524

### PR DESCRIPTION
**Pull request by marcmognol**
### Disable CS0436 warnings for TextColorTo() extension ###

 

 ### Linked Issues ###
 

 - Fixes #411 
 - Fixes #527

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

 

Tests for #527  

Before this amazing fix:

image

After this amazing fix: 
image

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks @marcmognol!

It looks like this PR suppresses the warning.

@pictos - as our resident Roslyn expert (at least, you’re an expert compared to me!), is there a way to fix the root cause of the warning?

**Comment by marcmognol** [comment]
Hi,

I am aware that PR doesn't fix the root of this issue but warnings will disappear.

**Comment by pictos** [comment]
@marcmognol thanks for you PR. I'll have time to review it during next week. I'll reach out to you if I found something that we can improve

**Comment by pictos** [comment]
@marcmognol I tested on my end and no more warnings and also should fix another issue (:
Thanks for your contribution!

**Comment by brminnick** [comment]
@pictos I don't recommend that we merge this because it hides the root cause. 

This PR doesn't fix the root cause.

**Comment by pictos** [comment]
@brminnick my bad, I thought that I pushed the changes here, one sec I'll fix it

**Comment by pictos** [comment]
@brminnick looks like it updated on my browser now... So if you see the changed files I just added `auto-generated` flag on my PR here.

**Review by brminnick — APPROVED** [review]
Thanks Pedro!

**Pull request merged**
