### PR TITLE
Added auto-generated flag

### LINKED ISSUE #527: [Bug] Analyzers don't like our SG code style
For more info, see #524

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

Add a simple comment to make analyzers happy! 

 ### Linked Issues ###
 

 - Fixes #527

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

 

Before my amazing fix:

image

After my huge fix: 
image

The 20 errors are on MAUI classes, nothing to do with us

### CODE REVIEW

**Comment by pictos** [comment]
Closing this in favor of #508 (community PR)

**Comment by pictos** [comment]
Closing this in favor of #508 (community PR)

**Comment by brminnick** [comment]
I recommend that we merge this and close #508

**Comment by JustinC-IADS** [comment]
@brminnick , @pictos , any update on this? I'm curious why this proposal was closed.

**Comment by brminnick** [comment]
This was implemented in https://github.com/CommunityToolkit/Maui/pull/508

**Comment by JustinC-IADS** [comment]
Ok. Thanks. I'm assuming it just hasn't made it into the NuGet release yet.

**Pull request closed without merging**
