### PR TITLE
Fix Popup MapOnClosed Android crash

### LINKED ISSUE #707: [BUG] Android Popup crash when switching tabs in AppShell
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Maui Application crashes when switching tabs on Android with a popup opened

### Expected Behavior

It should not crash :)

### Steps To Reproduce

1. Create a MAUI AppShell application with 2 tabs.

2. Inside one of the tabs open a Popup

3. Switch the tabs on an Android device

I have not tested on any other platform yet other than Android

### Link to public reproduction project repository

Easy to reproduce

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Android 
- .NET MAUI: 7.0.0.-rc2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by danardelean**
### Description of Change ###

Scenario: 

MAUI AppShell with a TabBar with at least two pages. In one of the pages open a Popup with ShowPopupAsync and, without closing the popup, switch to the other tab. The application will crash on Android on MapOnClosed because the native view (Java object) have been already disposed

I haven't test it on other platforms (just Android) to see if the problem exists in the other handlers

 ### Linked Issues ###
Haven't opened one yet

 - Fixes #707
The application will not crash on Android anymore

 ### PR Checklist ###

 - [X] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 Not yet approved but check if it changed
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Easy to reproduce
 - [X] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard]
 No as it uses the ! operator but you could change it The bug is pretty nasty
 - [ ] Documentation created or updated: 
 No change to the API 

 ### Additional information ###

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
Please follow the flow of PR checklist, otherwise the PR will be closed

**Comment by VladislavAntonyuk** [comment]
@danardelean we highly ask you to follow the flow, described in readme. when you create the issue and it is approved we can reopen this PR. Closing it for now

**Comment by brminnick** [comment]
Yes, please open an issue with a reproduction sample so that we can confirm the bug and confirm this PR fixes it!

We can reopen this same PR to avoid duplicating efforts once we have a reproduction sample.

**Comment by pictos** [comment]
Hey team, there's an issue. I updated the PR description. Just waiting for the repro.

**Comment by brminnick** [comment]
Closing as #707 confirms the intended behavior

**Pull request closed without merging**
