### PR TITLE
122 UniformGrid

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
## Fixes

#122 

## Description

Migrate UniformGrid to MCT
image

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
I added samples in this PR (https://github.com/CommunityToolkit/Maui/pull/5)
So decided to keep it in 1 review and add samples for UniformGrid later

**Comment by pictos** [comment]
Hey, @VladislavAntonyuk hope that you're doing fine. I have a couple of comments on this PR, one brings up our new contribution flow and the other about the implementation.

Not sure you saw our [latest Community Stand-up](https://youtu.be/3XSIcI466rA?t=1100) where @brminnick showed our contribution process. The contribution process changed from the old XCT.

The first step is to ask in the issue to work on it and wait for us to confirm that you can work on that issue, this will help us to keep everything on track.

About the code implementation, the Layout API was changed in the .NET MAUI, this one is the legacy API with that I believe that we want to migrate this layout to the newest API.

Happy to see that we will have your contributions here as well <3

**Comment by brminnick** [comment]
> @brminnick the implementation is updated to remove Xamarin compatibility namespace. is DoNotMerge label still valid? (I just don't like this name 😄 )

Once @jsuarezruiz removes the `help wanted` tag and assigns it to you, we can remove the `do not merge` tag

**Comment by brminnick** [comment]
Unblocking this now that .NET MAUI supports Unit Tests 🎉

**Comment by brminnick** [comment]
FYI - 2 of the new UniformGrid UnitTests are failing in the CI Pipeline:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.29]     CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.MeasureUniformGrid [FAIL]
[xUnit.net 00:00:01.30]     CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.ArrangeChildrenUniformGrid [FAIL]
  Failed CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.MeasureUniformGrid [50 ms]
  Error Message:
   Assert.Equal() Failure
Expected: {Width=75 Height=75}
Actual:   {Width=-0 Height=0}
  Stack Trace:
     at CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.MeasureUniformGrid() in /Users/runner/work/1/s/src/CommunityToolkit.Maui.UnitTests/Views/UniformGrid_Tests.cs:line 36
  Failed CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.ArrangeChildrenUniformGrid [2 ms]
  Error Message:
   Assert.Equal() Failure
Expected: {Width=25 Height=25}
Actual:   {Width=-3.4924596548080444E-08 Height=0}
  Stack Trace:
     at CommunityToolkit.Maui.UnitTests.Views.UniformGridTests.ArrangeChildrenUniformGrid() in /Users/runner/work/1/s/src/CommunityToolkit.Maui.UnitTests/Views/UniformGrid_Tests.cs:line 44

Failed!  - Failed:     2, Passed:   275, Skipped:     0, Total:   277, Duration: 16 s - /Users/runner/work/1/s/src/CommunityToolkit.Maui.UnitTests/bin/Release/net6.0/CommunityToolkit.Maui.UnitTests.dll (net6.0)
```

**Comment by VladislavAntonyuk** [comment]
@brminnick , @jsuarezruiz tests are fixed. 
As for the discussion about MaxRows and MaxColumns, I suggest to not put it in this PR. This one is about migration without adding a new functionality

**Comment by brminnick** [comment]
> @brminnick , @jsuarezruiz tests are fixed.

Thanks!! 

> As for the discussion about MaxRows and MaxColumns, I suggest to not put it in this PR. This one is about migration without adding a new functionality

I defer to the Proposal Champion, @jsuarezruiz, but I vote to include `MaxRows` and `MaxColumns` it in this PR (assuming that was the verdict in the discussion). 

We really don't have the concept of "Migration PRs"; instead, we are viewing each new .NET MAUI Community Toolkit feature as a brand new feature, and if we can tweak/update/fix its similar implementation from Xamarin.CommunityToolkit, we should do it 💯

**Comment by VladislavAntonyuk** [comment]
Added as a separate commit.

**Comment by VladislavAntonyuk** [comment]
@brminnick , @jsuarezruiz could you please review? it also adds Views sample. so we do not need to copy the code between different PRs. thank you

**Comment by brminnick** [comment]
@jsuarezruiz - friendly reminder to review this PR ❤️ 

Any chance you can take a look this weekend?

**Pull request merged**
