### PR TITLE
Compareconverter sample

### PR DESCRIPTION
**Pull request by marsscotia**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
Hi @marsscotia! Did you inten too close this PR?

**Comment by marsscotia** [comment]
@brminnick Yes, I hadn't intended to open it quite yet, it wasn't ready. Too click happy!

**Comment by bijington** [comment]
@marsscotia if it helps you can open a PR in draft.

**Comment by marsscotia** [comment]
@bijington That's great, thanks! Still very much getting to grips with GitHub so all advice appreciated. :)

**Pull request closed without merging**
