### PR TITLE
Fix 827

### LINKED ISSUE #827: [BUG] The popup is not centered horizontally in the app window on Mac OS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The maui toolkit popup **is not centered** horizontally in the app window on Mac OS.

Screenshot 2022-12-13 at 7 18 38 PM

### Expected Behavior

The popup should be centered horizontally in the app window by default.

### Steps To Reproduce

- Create .NET 7 net maui project from Visual Studio 2022 template
- Add nuget package CommunityToolkit.Maui version 3.1.0
- Create "SomePopup"
- Update SomePopup.xaml and Somepopup.xaml.cs to toolkit Popup
- Show popup on button click

### Link to public reproduction project repository

https://github.com/dekipet/MAUIPopupBug

### Environment

```markdown
- NET MAUI CommunityToolkit: 3.1.0
- OS: Mac OS Ventura 13.0.1 
- NET: 7.0
```

### Anything else?

On Windows 10 it is working as expected, popup is centered by default.

### PR DESCRIPTION
**Pull request by jaigupta91**
### Description of Change ###

Fixed 827 issue

 ### Linked Issues ###

 - Fixes #827

### CODE REVIEW

**Review by pictos — CHANGES_REQUESTED** [review]
@jaigupta91 thanks for that. I tested the samples and there are some popups that don't show up on the screen. Can you take a look?

**Comment by jaigupta91** [comment]
@pictos I have fixed that. I have pushed changes Please check and let me know if i missed something.

**Comment by jaigupta91** [comment]
@pictos I have fixed that. I have pushed changes. Please check and let me know if i missed something.

**Review by pictos — COMMENTED** [review]
@jaigupta91 the MultipleButtonPopup sample still has the issue, as you can see in the screenshot

Screenshot 2022-12-16 at 12 18 03

**Comment by jaigupta91** [comment]
It's due to your window size. Just increase your window size by dragging Or decrease the size in sample.
MultipleButtonPopup.xaml.cs
 - Size = popupSizeConstants.Small; (Changed size from medium to small)

**Comment by jaigupta91** [comment]
@pictos Above solution helped to showing popup to you?

**Comment by pictos** [comment]
@jaigupta91 I'll take another look during the week, I can't look this weekend

**Review by pictos — APPROVED** [review]
@jaigupta91 Thanks for this PR. I made a little change to simplify it a little bit. If you want to test and see if I didn't break anything, let me known, then I'll merge after your review (:

**Comment by jaigupta91** [comment]
Thanks for the changes. I tested it and it's working fine.

**Comment by pictos** [comment]
With that I'll merge this one before my flight (:.
Thanks again❣️

**Pull request merged**
