### PR TITLE
Full screen for Media Element on Android

### PR DESCRIPTION
**Pull request by vhugogarcia**
### Description of Change ###

Enables the simple full screen feature for the media element on Android devices. iOS already have the full screen feature natively, this is purely for Android since this feature requires custom implementation. It uses the ExoPlayer _StyledPlayerView_.

 ### Linked Issues ###
None

 ### Additional information ###

It appears to be a bug in .NET MAUI where the Shell Navigation Bar visibility does not change in Android when trying to hide them using the following code: [Platform.CurrentActivity.Window.InsetsController?.Hide(WindowInsets.Type.SystemBars());](https://github.com/vhugogarcia/CommunityToolkitMaui/blob/3736251dced83f42706b9685a7d5118c1b532eb8/src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.android.cs#L91). However, I have not reported this as a bug on the MAUI repository until I heard from your feedback, because maybe I'm missing something.

As a workaround, I had to set `Shell.NavBarIsVisible="False"` in the `Pages/Views/MediaElementPage.xaml` sample file, temporary just to demo it.

I think this full screen feature can be gratefully improved by adding the following features:

- **IsFullScreen** property, where the user can know when the video is playing in full screen or no. _I tried already without luck  :(_ 
- **SetFullScreen(true/false)** method, where the user can programmatically set the video in full screen or no.
 

> If there is a bug in .NET MAUI when setting the nav bar visibility in Android, then the IsFullScreen property can be used to hide it on the content page under MAUI Essentials DisplayInfoChanged method.

https://user-images.githubusercontent.com/1047398/218768324-6f1e079d-371d-43d3-b4b1-738be4b8dfa0.mp4

Please feel free to contribute as well, I am happy to learn!

Thanks in advance 👍🏻

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks @vhugogarcia!

It looks like you skipped a few steps in our process to [Add A New Feature](https://github.com/CommunityToolkit/Maui#submitting-a-new-feature). 

Please start by opening a [Discussion](https://github.com/CommunityToolkit/Maui/discussions/new?category=new-feature-discussions) if you haven't already. 

Every new feature should start as a Discussion: https://github.com/CommunityToolkit/Maui/discussions/new?category=new-feature-discussions

Once the feature has been fleshed out, we then open a Proposal: https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=new%2Cproposal&template=open-a-new-feature-proposal.yml&title=%5BProposal%5D+

**Comment by brminnick** [comment]
Adding https://github.com/CommunityToolkit/Maui/labels/do%20not%20merge until the New Feature Proposal has been approved

**Comment by vhugogarcia** [comment]
> Thanks @vhugogarcia!
> 
> It looks like you skipped a few steps in our process to [Add A New Feature](https://github.com/CommunityToolkit/Maui#submitting-a-new-feature).
> 
> Please start by opening a [Discussion](https://github.com/CommunityToolkit/Maui/discussions/new?category=new-feature-discussions) if you haven't already.
> 
> Every new feature should start as a Discussion: https://github.com/CommunityToolkit/Maui/discussions/new?category=new-feature-discussions
> 
> Once the feature has been fleshed out, we then open a Proposal: https://github.com/CommunityToolkit/Maui/issues/new?assignees=&labels=new%2Cproposal&template=open-a-new-feature-proposal.yml&title=%5BProposal%5D+

Thanks @brminnick for the feedback. I went ahead and created this discussion: https://github.com/CommunityToolkit/Maui/discussions/995 

I apologize for doing it the wrong way.

**Comment by vhugogarcia** [comment]
@dotnet-policy-service agree

**Comment by vhugogarcia** [comment]
I closed this merge, because, we need a better solution for full screen on android devices. I will post the details found on the discussion board.

Thanks all!! :)

**Pull request closed without merging**
