### PR TITLE
Improve Windows sample app UI

### PR DESCRIPTION
**Pull request by mhrastegari**
### Description of Change ###
Changing Shell Flyout behavior and style on WinUI version of sample app

 ### Linked Issues ###
 - Fixes #1860

 ### PR Checklist ###
 - [x] Has a linked Issue/Discussion and has been `approved
 - [x] Rebased on top of `main` at time of PR

 ### Additional information ###

New look:

Dark:

Screenshot (30)

Light:

Screenshot (31)

### CODE REVIEW

**Comment by mhrastegari** [comment]
@dotnet-policy-service agree

**Comment by jfversluis** [comment]
This is amazing @mhrastegari thank you so much! One very much nitpicky thing... The space between the "cards" on the right seems a bit much? I feel it could look even a little bit better even if that was a bit less? But I am in no way a designer so maybe I'm very wrong too 😄

**Comment by mhrastegari** [comment]
Surprisingly in my opinion it's well spaced 😅
it's kinda like what we have in Windows 11 settings

image

**Comment by jfversluis** [comment]
I mean this

image

**Comment by mhrastegari** [comment]
Yeah agreed 👍🏻🚀
I'll fix it now

**Review by brminnick — APPROVED** [review]
So good!! Thanks @mhrastegari!

**Pull request merged**
