### PR TITLE
CODE RUB: Simple Exception Syntax Error.

### LINKED ISSUE #612: [BUG] Simple Exception Syntax Error.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The exception message should be corrected for syntax.

### Expected Behavior

 Letter case should be default case, old version is pascal case...

### Steps To Reproduce

1.Open and run solution fron reproduction repository.
2.If you get an exception message when you run the program, there are syntax errors.

### Link to public reproduction project repository

No

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Rashidovicc**
### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #612 

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/XYZ 

 ### Additional information ###

 
 
close #612

### CODE REVIEW

**Comment by Rashidovicc** [comment]
@VladislavAntonyuk As you said, I solved the syntax exception message problems completely.

**Comment by VladislavAntonyuk** [comment]
Start with reading readme.

**Comment by Rashidovicc** [comment]
@VladislavAntonyuk Can you help me if I can open a discussion, then briefly, will you approve and merge?

**Comment by Rashidovicc** [comment]
@VladislavAntonyuk  I created a Discussion.

**Comment by Rashidovicc** [comment]
@VladislavAntonyuk As you said, I opened a discussion, will it be considered, maybe it will take a long time, but all the tests passed.

**Comment by VladislavAntonyuk** [comment]
Please update PR template. Link the issue

**Comment by Rashidovicc** [comment]
> Please update PR template. Link the issue.
Sorry to bother you, did I do as you said? I wrote the link to the issue in the PR. I apologize for asking so many questions.

**Comment by Rashidovicc** [comment]
@VladislavAntonyuk Hi How are you 

It possible please to take label 
image

If you to take this label show my commits

**Pull request merged**
