### PR TITLE
BadgeView

### PR DESCRIPTION
**Pull request by jsuarezruiz**
## Description

Port BadgeView from XCT.

### CODE REVIEW

**Comment by brminnick** [comment]
FYI - there are merge conflicts that need to be resolved

**Comment by tnassour** [comment]
Hello, when this merge request will be done ?

**Comment by brminnick** [comment]
Hi @tnassour! Would you like to take over this PR?

This PR has gone `stale` (no activity in 30+ days) and we've added the `Help Wanted`. We are looking for someone to continue + finish the work started here.

**Comment by tnassour** [comment]
I don't havez the rights to push a branch on this repository

**Comment by brminnick** [comment]
Sorry, yes, you'll first need to Fork this repository.

Here's the steps to follow:
1. Fork this repository: https://docs.github.com/en/get-started/quickstart/fork-a-repo
2. Create a new branch on your fork
3. Copy/paste your code into your new branch
4. Commit the new code to your branch
5. Push the new commit to GitHub
6. Open a new Pull Request to this repo from your branch: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by tnassour** [comment]
I am getting this error while trying to build the solution without any modification : is it normal ?

**Comment by tnassour** [comment]
I have opened a new Pull request we can change the discussion to the other Thread
https://github.com/CommunityToolkit/Maui/pull/345

**Comment by brminnick** [comment]
Closing in favor of https://github.com/CommunityToolkit/Maui/pull/345

**Pull request closed without merging**
