### PR TITLE
StateContainer, Add `ChangeStateWithAnimation()`

### LINKED ISSUE #942: [BUG] StateContainer crash app when state change too fast
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

I am currently testing the state container on WinUI and triggering the states by using windows size changed, I notice when I change the size slowly everything works perfectly but when I resize the windows which trigger the state jump between states too fast the app crash, I only tested it on Windows so I am don't whether this behavior is occurring on IOS or Android

### Expected Behavior

App not crash

### Steps To Reproduce

```cs
private void BasePage_SizeChanged(object sender, EventArgs e)
    {
        if (Window.Width < 500)
        {
            _vm.CurrentState = "Phone";
            return;
        }
        else if (Window.Width < 900)
        {
            _vm.CurrentState = "Tablet";
            return;
        }
        else if (Window.Width < 2000)
        {
            _vm.CurrentState = "Desktop";
            return;
        }
    }
```

```xml
 <ScrollView>
        <Grid
            toolkit:StateContainer.CanStateChange="{x:Binding CanStateChange}"
            toolkit:StateContainer.CurrentState="{x:Binding CurrentState}"
            toolkit:StateContainer.ShouldAnimateOnStateChange="True">
            <toolkit:StateContainer.StateViews>
                <app:ChatPagePhoneLayout toolkit:StateView.StateKey="Phone" />
                <app:ChatPageTabletLayout toolkit:StateView.StateKey="Tablet" />
                <app:ChatPageDesktopLayout toolkit:StateView.StateKey="Desktop" />
            </toolkit:StateContainer.StateViews>
        </Grid>
    </ScrollView>
```

```xml
<ContentView
    x:Class="MAUIsland.ChatPagePhoneLayout"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit">

    <ContentView.Resources>
        <x:Array x:Key="PropertyItemsSource" Type="{x:Type x:String}">
            <x:String>
                <![CDATA[
                                <strong style="color:blue">BorderColor</strong>, of type <strong style="color:blue">Color</strong>, describes the border color of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">BorderWidth</strong>, of type <strong style="color:blue">double</strong>, defines the width of the button's border.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CharacterSpacing</strong>, of type <strong style="color:blue">double</strong>, defines the spacing between characters of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Command</strong>, of type <strong style="color:blue">ICommand</strong>, defines the command that's executed when the button is tapped.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CommandParameter</strong>, of type <strong style="color:blue">object</strong>, is the parameter that's passed to Command.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ContentLayout</strong>, of type <strong style="color:blue">ButtonContentLayout</strong>, defines the object that controls the position of the button image and the spacing between the button's image and text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CornerRadius</strong>, of type <strong style="color:blue">int</strong>, describes the corner radius of the button's border.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontAttributes</strong>, of type <strong style="color:blue">FontAttributes</strong>, determines text style.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontAutoScalingEnabled</strong>, of type <strong style="color:blue">bool</strong>, defines whether the button text will reflect scaling preferences set in the operating system. The default value of this property is true.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontFamily</strong>, of type <strong style="color:blue">string</strong>, defines the font family.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontSize</strong>, of type <strong style="color:blue">double</strong>, defines the font size.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ImageSource</strong>, of type <strong style="color:blue">ImageSource</strong>, specifies a bitmap image to display as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">LineBreakMode</strong>, of type <strong style="color:blue">LineBreakMode</strong>, determines how text should be handled when it can't fit on one line.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Padding</strong>, of type <strong style="color:blue">Thickness</strong>, determines the button's padding.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Text</strong>, of type <strong style="color:blue">string</strong>, defines the text displayed as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextColor</strong>, of type <strong style="color:blue">Color</strong>, describes the color of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextTransform</strong>, of type <strong style="color:blue">TextTransform</strong>, defines the casing of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ImageSource</strong>, of type <strong style="color:blue">ImageSource</strong>, specifies a bitmap image to display as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">LineBreakMode</strong>, of type <strong style="color:blue">LineBreakMode</strong>, determines how text should be handled when it can't fit on one line.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Padding</strong>, of type <strong style="color:blue">Thickness</strong>, determines the button's padding.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Text</strong>, of type <strong style="color:blue">string</strong>, defines the text displayed as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextColor</strong>, of type <strong style="color:blue">Color</strong>, describes the color of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextTransform</strong>, of type <strong style="color:blue">TextTransform</strong>, defines the casing of the button's text.
                            ]]>
            </x:String>
        </x:Array>
    </ContentView.Resources>

    <VerticalStackLayout Spacing="10">
        <Frame Style="{x:StaticResource DocumentContentFrameStyle}">
            <CollectionView
                Footer="{x:StaticResource PropertiesListFooter}"
                Header="{x:StaticResource PropertiesListHeader}"
                ItemsSource="{x:StaticResource PropertyItemsSource}"
                Style="{x:StaticResource PropertiesListStyle}" />
        </Frame>
        <Editor HeightRequest="50" Placeholder="Enter message" />
    </VerticalStackLayout>
</ContentView>
```

### Link to public reproduction project repository

None

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0
- OS: Window
- .NET MAUI: 7.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change ###

Instead of throwing exceptions, just return. The animation operation is canceled but we still can continue going to the next state.

 ### Linked Issues ###
 

 - Fixes #942, #1027 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [x] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/235 

 ### Additional information ###

### CODE REVIEW

**Comment by brminnick** [comment]
Hey Vlad! The experience described in the Issue is the expected behavior. 

We added `CanStateChange` and documented how to use it in the docs to avoid this Exception:

https://learn.microsoft.com/dotnet/communitytoolkit/maui/layouts/statecontainer#viewmodel

**Comment by brminnick** [comment]
The fix for https://github.com/CommunityToolkit/Maui/issues/942 should be specific to resizing the Window on WinUI.

**Review by brminnick — APPROVED** [review]
Thanks Vlad! 

I added some tests to ensure/verify that the user can't change `CurrentState` while the animations are running.

Check out the code I added to ensure it looks good. 

I'll approve this, and if you think it looks good, you can go ahead and merge it 🙌

**Comment by brminnick** [comment]
@bijington Are you able to help with updating the docs?

### Removed APIs

```cs
StateContainer.ShouldAnimateOnStateChangeProperty
```

### Added APIs

```cs
/// <summary>
/// Change state with custom animation.
/// </summary>
public static async Task ChangeStateWithAnimation(
 		BindableObject bindable,
 		string? state,
 		Animation? beforeStateChange,
 		Animation? afterStateChange,
 		CancellationToken token);

/// <summary>
/// Change state with custom animation.
/// </summary>
public static async Task ChangeStateWithAnimation(
 		BindableObject bindable,
 		string? state,
 		Func<VisualElement, CancellationToken, Task>? beforeStateChange,
 		Func<VisualElement, CancellationToken, Task>? afterStateChange,
 		CancellationToken cancellationToken);

/// <summary>
/// Change state using the default fade animation.
/// </summary>
public static async Task ChangeStateWithAnimation(BindableObject bindable, string? state, CancellationToken token);
```

**Comment by brminnick** [comment]
> [Removed APIs](https://github.com/CommunityToolkit/Maui/pull/1021#issuecomment-1445468285)

^ FYI @jfversluis This is a breaking change that we'll need to note in the release notes for v5.0.0

**Comment by VladislavAntonyuk** [comment]
new docs: https://github.com/MicrosoftDocs/CommunityToolkit/pull/235

**Review by brminnick — APPROVED** [review]

**Comment by Strypper** [comment]
Thanks guys really appreciate your work.

**Pull request merged**
